### PR TITLE
update(window_size): Fix window size if it is maximized on login

### LINKED ISSUE #821: bug(resize): if you start the app in a bigger size, doesn't resize properly
STR:
- cargo run
- maximize app
- enter app
- appears like this

macOS, m1

https://github.com/Satellite-im/Uplink/assets/29093946/f9ffcd9c-fe1d-4eda-8161-6d3a546998fc

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix window size if user maximize it on login 

https://github.com/Satellite-im/Uplink/assets/63157656/d73b91ca-30f3-4569-ab87-24914f819d29

### Which issue(s) this PR fixes 🔨

- Resolve #821

### CODE REVIEW

**Comment by stavares843** [comment]
**AI CODE REVIEW**

Feedback on the code changes:

Patch 1/2:

The code changes in common/src/state/ui.rs add four new fields to the UI struct: window_maximized, window_width, window_height, and metadata.
The changes in ui/src/layouts/loading.rs update the window size if it is maximized.
This change is implemented correctly, setting the inner size of the desktop to the stored window width and height when the window is maximized.
The changes in ui/src/layouts/unlock.rs update the window size if it is maximized.
This change is also implemented correctly, setting the window_height and window_width fields of the UI struct based on the outer size of the desktop when the unlock process is complete.
Patch 2/2:

The code changes in ui/src/layouts/unlock.rs appear to be purely whitespace formatting changes.
Overall, the code changes seem fine:

The changes in ui/src/layouts/loading.rs and ui/src/layouts/unlock.rs correctly handle updating the window size when it is maximized.
Patch 2/2 is a minor formatting change.
No bugs or issues were found, and the code appears to do what it says in the commit messages. Well done!

**Comment by phillsatellite** [comment]
When I switched to this branch, I lost all my active chats that were in my sidebar previously. This happened on all OS's and I replicated multiple times 

Screenshot 2023-06-05 at 12 43 21 PM

**Comment by lgmarchi** [comment]
> When I switched to this branch, I lost all my active chats that were in my sidebar previously. This happened on all OS's and I replicated multiple times
> 
> Screenshot 2023-06-05 at 12 43 21 PM

@phillsatellite When we back to dev, your chats back to normal?

**Comment by phillsatellite** [comment]
> > When I switched to this branch, I lost all my active chats that were in my sidebar previously. This happened on all OS's and I replicated multiple times
> > Screenshot 2023-06-05 at 12 43 21 PM
> 
> @phillsatellite When we back to dev, your chats back to normal?

@lgmarchi 
No when I switch back to dev all chats are still missing forcing user to re open the chats from going to Friends -> Click "chat" on one of the friends I had an active chat with before 

How I tested this was:
-Start on dev branch with all active chats in sidebar 
-Switch to any other PR to verify that all active chats are still in the Sidebar
-Switch back to dev verify that active chats are still there after checking out other PR 
-Now with all active chats still in sidebar I switch from Dev branch to this PR
-All active chats will be missing 

I did this on Linux, Windows and Mac

**Comment by dariusc93** [comment]
> > > When I switched to this branch, I lost all my active chats that were in my sidebar previously. This happened on all OS's and I replicated multiple times
> > > Screenshot 2023-06-05 at 12 43 21 PM
> > 
> > 
> > @phillsatellite When we back to dev, your chats back to normal?
> 
> @lgmarchi No when I switch back to dev all chats are still missing forcing user to re open the chats from going to Friends -> Click "chat" on one of the friends I had an active chat with before
> 
> How I tested this was: -Start on dev branch with all active chats in sidebar -Switch to any other PR to verify that all active chats are still in the Sidebar -Switch back to dev verify that active chats are still there after checking out other PR -Now with all active chats still in sidebar I switch from Dev branch to this PR -All active chats will be missing
> 
> I did this on Linux, Windows and Mac

You would need to clear out your state.json file. That would restore your chats

**Review by sdwoodbury — CHANGES_REQUESTED** [review]
in `loading.rs` on line 15 there is a `use_future` assigned to `desktop_resized`. I believe that the changes from lines 36-42 should go within that `use_future`.

**Comment by stavares843** [comment]
@sdwoodbury requesting your review regarding your latest comment

**Comment by stavares843** [comment]
@lgmarchi is this ready to test again? 🔨

**Comment by lgmarchi** [comment]
> @lgmarchi is this ready to test again? 🔨

Not yet, I am trying to understand @phillsatellite bug

**Review by sdwoodbury — APPROVED** [review]

**Comment by phillsatellite** [comment]
> 

Can I help out with explaining it more @lgmarchi ?

**Comment by dariusc93** [comment]
@lgmarchi its not a bug really but rather that youre adding additional fields to the state via `UI`, which is not available in dev so when it is serialized into the struct, it would error out and cause things not to load because of those fields missing. Adding `#[serde(default)]` to those new fields would cause it to be default if its not available. Other option would be to use `Option<T>`, though the former should suffice.

**Comment by lgmarchi** [comment]
> @lgmarchi its not a bug really but rather that youre adding additional fields to the state via `UI`, which is not available in dev so when it is serialized into the struct, it would error out and cause things not to load because of those fields missing. Adding `#[serde(default)]` to those new fields would cause it to be default if its not available. Other option would be to use `Option<T>`, though the former should suffice.

I arrived in this conclusion right now hahaha Thanks @dariusc93, so @phillsatellite  and @stavares843 branch is good to go

**Comment by phillsatellite** [comment]
On MacOS this is now working as intended, thanks Lucas! 

We do have an issue on Windows still, after you enter PIN the app window will move across the screen forcing user to drag it back to center 


https://github.com/Satellite-im/Uplink/assets/93608357/1b500ab3-f6d0-4cba-8c32-8efebe6f43ec

**Comment by lgmarchi** [comment]
> On MacOS this is now working as intended, thanks Lucas!
> 
> We do have an issue on Windows still, after you enter PIN the app window will move across the screen forcing user to drag it back to center
> 
>  Recording.2023-06-09.164416.mp4

@phillsatellite I am not with my windows machine here, but I will get it to solve this problem

**Review by dariusc93 — APPROVED** [review]

**Comment by phillsatellite** [comment]
@lgmarchi I tested with the most recent commits and had a minor issue 

On Mac and Linux when you exit fullscreen it will re-size to what seems to be to the Tablet view 

https://github.com/Satellite-im/Uplink/assets/93608357/e48c6219-7e9e-4da5-b70d-b07b63ac49e8

On Windows when you try to exit fullscreen it makes an animation like its going to exit fullscreen but just remain in fullscreen view

https://github.com/Satellite-im/Uplink/assets/93608357/ed59004f-e791-4e3d-9c49-3e76501eae7b

**Comment by lgmarchi** [comment]
> @lgmarchi I tested with the most recent commits and had a minor issue
> 
> On Mac and Linux when you exit fullscreen it will re-size to what seems to be to the Tablet view
> 
>  Screen.Recording.2023-06-20.at.4.15.11.PM.mov 
> On Windows when you try to exit fullscreen it makes an animation like its going to exit fullscreen but just remain in fullscreen view
> 
>  20230620-2017-31.5421030.mp4

Windows is wrong. 

MacOS and Linux are working this on Dev as well, and because of min inner size defined, do you want to change that?

**Comment by lgmarchi** [comment]
> @lgmarchi I tested with the most recent commits and had a minor issue
> 
> On Mac and Linux when you exit fullscreen it will re-size to what seems to be to the Tablet view
> 
>  Screen.Recording.2023-06-20.at.4.15.11.PM.mov 
> On Windows when you try to exit fullscreen it makes an animation like its going to exit fullscreen but just remain in fullscreen view
> 
>  20230620-2017-31.5421030.mp4

Fixed on both systems, ready for testing again!

**Comment by phillsatellite** [comment]
Like Lucas had mentioned to me in a DM there is a small glitch on MacOS the first time you minimize out of fullscreen but after the first time works perfectly along with the other OS's. No need to hold up the PR any longer for a small glitch on MacOS. Thanks @lgmarchi awesome pr! 🔥 

https://github.com/Satellite-im/Uplink/assets/93608357/31d46b39-0bf9-4d68-b0eb-03631f808546

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
