### PR TITLE
update(React): Let react disabled if user disable emoji extension

### LINKED ISSUE #1487: bug(react): appears when the emoji extension is not enabled
image

the `+` button also needs to be hidden when the emoji picker is not enabled.

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1487

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
@luisecm noticed the following


in dev if we do make dmg we get the emojis extension by default

image


in this branch if we do make dmg we dont get the emoji extension by default

image

**Comment by lgmarchi** [comment]
> @luisecm noticed the following
> 
> in dev if we do make dmg we get the emojis extension by default
> 
> image
> 
> in this branch if we do make dmg we dont get the emoji extension by default
> 
> image

Interesting, let me take a look.

**Review by sdwoodbury — APPROVED** [review]

**Comment by stavares843** [comment]
@coderabbitai resolve

**Comment by stavares843** [comment]
added changes requested due to linter failing

**Pull request merged**
