### PR TITLE
fix(blink): allow audio i/o devices which use 2 input/output channels

### LINKED ISSUE #315: bug(calling): Sheldon's windows PC can't send or receive audio
Not sure exactly when this became an issue because ***someone*** never filed a bug report. 

The on the user's device, the` audio-codec-cli` can successfully record and play audio after setting the number of audio channels to 2. (Note that Uplink shouldn't have a problem with unsupported audio I/O configurations because it performs a check changes the configuration if needed). 

User observed this error message: `failed to send sample: ...` which happens when the audio queue is full for a sink track (which deals with receiving audio from someone else).

The audio source track implementation doesn't log when the queue is full. it's possible that the same thing is happening for the source track. 

 It seems like for the sink track, the CPAL stream isn't playing... `build_output_stream` receives a callback which should poll the queue at the audio sampling rate - 48Khz.

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

-  allow audio i/o devices which use 2 input/output channels. ex: a 2 channel microphone
- changes the logic for automatically ending a call - as far as Uplink is concerned, a `CallTerminated` event is now emitted and Uplink doesn't need to worry about the logic to automatically end a call. 

### Which issue(s) this PR fixes 🔨

- Resolve [#315](https://github.com/Satellite-im/Warp/issues/315)

### Testing

- [x]  initiate  a call with a microphone that uses 2 input channels. there should be no error from the warp library, regarding  the call, and participants should be able to speak to each other.
- [x] initiate a call with a microphone that uses 1 input channel.  there should be no error from the warp library, regarding  the call, and participants should be able to speak to each other
- [ ] have a 2 person call, 1 participant leaves, the other should see Uplink end the call automatically. 
- [ ] have a 2 person group call, 1 person leaves, the other should see Uplink end the call automatically. 
- [ ]  have a 3 person group call with at least 2 persons joined. One person leaves. Uplink shouldn't automatically end the call.

note that for determining how many channels your microphone has, in `warp/tools/blink-cli` there following command can be used: `supported-input-configs`.

### CODE REVIEW

**Comment by phillsatellite** [comment]
On MacOS, when you compile and try to login its a never ending loading page. This is not able to be replicated on Windows and Linux. 


https://github.com/Satellite-im/Uplink/assets/93608357/9bb30e67-9bfc-4f75-b3a0-12e166a46322

**Comment by sdwoodbury** [comment]
~~@phillsatellite I got that too but there is an error message about State.json failing to deserialize. that isn't related to this PR.~~ and it still failed even with that file deleted :sweat:

**Comment by sdwoodbury** [comment]
note that unrelated changes to Uplink cause a panic in the emoji extension. for testing, delete that extension.

**Comment by dariusc93** [comment]
Blocked until #1175 is merged

**Review by dariusc93 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
