### PR TITLE
update(responsive): Change layout responsive manually

### LINKED ISSUE #128: App stays in mobile/desktop view when adjust browser size
**Issue:** If you are in mobile view and adjust your browser window to be bigger like the desktop view, the UI will still be rendered like you are in mobile view. This is the same if you are in desktop view and you adjust the browser window to be smaller like the mobile view, the UI will still be rendered for desktop view and not mobile. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/212104843-761c162f-e62c-44db-b6ff-9b95ee49600c.mov

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Possibility to change layout responsive manually 

https://user-images.githubusercontent.com/63157656/212139025-f7efd419-3aee-4cd0-9494-f2d4c9a2e75b.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #128

### CODE REVIEW

**Comment by phillsatellite** [comment]
Found a couple minor issues when testing

- When the user hits the mobile view button and then hovers they're curser anywhere over the app, the screen will stretch to the bottom

https://user-images.githubusercontent.com/93608357/212143658-2a322f1f-726a-4790-b7ec-093123f81184.mov

- I also wasn't able to get it to switch views when I would manually adjust it, in video I manually change it to mobile view but will still have desktop behavior 

https://user-images.githubusercontent.com/93608357/212144587-f8b5de77-5f32-4da7-a647-a86e41264b93.mov

**Comment by phillsatellite** [comment]
@lgmarchi fix worked great, I made one suggestion to have to Sidebar pop out automatically when manually going from Mobile to Desktop. He's gonna make that change and try to improve the code a little 👍 

https://user-images.githubusercontent.com/93608357/212153635-84c4b051-31ff-40f7-931c-9d9c6e7aa127.mov

**Comment by lgmarchi** [comment]
> @lgmarchi fix worked great, I made one suggestion to have to Sidebar pop out automatically when manually going from Mobile to Desktop. He's gonna make that change and try to improve the code a little 👍
> 
>  Screen_Recording_2023-01-12_at_1.47.55_PM.mov

Thanks for suggestion and bug found @phillsatellite. Changes made!

**Comment by InfamousVague** [comment]
Pausing

**Pull request closed without merging**
