### PR TITLE
update(Group): Create group without participants

### LINKED ISSUE #612: Chat - Create groups without participants
In the current implementation of uplink, the only way to create a group is with friends at the creation of the group. Uplink should have an option to create a group without participants to be able to add them later on (since there is no restriction in warp for the minimum amount of users for a group chat) 

~~Blocked awaiting on #545~~

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Create group without participants 

https://user-images.githubusercontent.com/63157656/234654233-9a1882fa-7e70-41d5-aeeb-912086b82797.mov

### 2. Create group with a name already 

https://user-images.githubusercontent.com/63157656/234654428-37c24fbd-2b39-4ef3-8376-f5790e0f8d9a.mov

### 3. Create several group with same participants 

https://user-images.githubusercontent.com/63157656/234654546-25516cb2-fd9f-4f96-8f8c-3b1989fa4ad9.mov

- 

### Which issue(s) this PR fixes 🔨

- Resolve #612

### CODE REVIEW

**Review by dariusc93 — APPROVED** [review]

**Comment by phillsatellite** [comment]
Hi @lgmarchi very cool PR I have just one suggestion, if the user types in a Group Chat name with incorrect format the group should not be created until correct format is added. After I created a group with a name 
"      ...." it was a little confusing when group was created but no name was there 

https://user-images.githubusercontent.com/93608357/234708663-a224bd3a-0c0e-4623-9d0d-0724091321d3.mov

**Comment by lgmarchi** [comment]
> Hi @lgmarchi very cool PR I have just one suggestion, if the user types in a Group Chat name with incorrect format the group should not be created until correct format is added. After I created a group with a name " ...." it was a little confusing when group was created but no name was there
> 
>  Screen.Recording.2023-04-26.at.4.45.54.PM.mov

Done my friend, added a notification when group name is invalid and user try to create group!

**Comment by phillsatellite** [comment]
Just one small thing my friend, it worked great with incorrect format for title but it never showed error message when I tried to do a name with just spaces. Do you think we should show error for name with just spaces or we should just create the group with no name? 

https://user-images.githubusercontent.com/93608357/234910580-22eee956-f9bd-4a7e-8690-e07fa262f0f6.mov

**Comment by dariusc93** [comment]
> Just one small thing my friend, it worked great with incorrect format for title but it never showed error message when I tried to do a name with just spaces. Do you think we should show error for name with just spaces or we should just create the group with no name?

Does the log give an error when you create a group with just spaces?

**Comment by lgmarchi** [comment]
> Just one small thing my friend, it worked great with incorrect format for title but it never showed error message when I tried to do a name with just spaces. Do you think we should show error for name with just spaces or we should just create the group with no name?
> 
>  Screen.Recording.2023-04-27.at.11.14.59.AM.mov

Fixed

**Pull request merged**
