### PR TITLE
feat(chat): Quick profile feature

### LINKED ISSUE #238: Chat - Add Quick Profile feature that we had in Core
**Task:** We want to add the same Quick Profile concept that we had in Core. While you were in chat, if you clicked the other users avatar a quick profile would pop up with the option to message the user. If the user clicked they're own 

**Screenshot:**
Quick Profile

https://user-images.githubusercontent.com/93608357/216454688-1ddec673-6941-4bd0-9687-a29b4d067f12.mov

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- When right clicking on profile picture opens up a menu to allow several actions.
  If that person has a profile and or banner it will be shown at the top

Screenshot from 2023-03-30 18-18-08

Note:
The profile button does currently nothing. In future maybe can show a popup similar to how discord does it.
The call button also does nothing as calling is not implemented yet.
Chat/Messaging via this menu is disabled if the user is already in a in a direct message with the other/is not a friend with that user.

### Which issue(s) this PR fixes 🔨

- Resolve #238

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]

**Comment by InfamousVague** [comment]
awesome feature!

**Comment by phillsatellite** [comment]
Really neat! I have a few suggestions, if you think would be easier to fix in separate tickets let me know and I will create them

1.  If the message is low enough to the bottom of the page the Quick Profile will render outside of the apps window 

https://user-images.githubusercontent.com/93608357/230393754-116dbb28-e2c7-4c12-a2c8-e0c816ee144f.mov

Screenshot 2023-04-06 at 8 59 45 AM

2. Status indicator will render in the middle of the users profile pic

Screenshot 2023-04-06 at 9 00 00 AM

3. Indicator will show as offline if the user sets a banner picture (this is if you are viewing your own quick profile)

Screenshot 2023-04-06 at 9 30 19 AM

4. Since we temp blocked the ability to voice/video call friends we should probably block the option to call from the Quick Profile 

Screenshot 2023-04-06 at 9 30 28 AM

**Comment by InfamousVague** [comment]
for the profile going off screen @Flemmli97 you can probably copy the code the context menu uses, I think it's a simple JS

**Comment by Flemmli97** [comment]
all points should be addressed now

**Comment by phillsatellite** [comment]
Send Kevin a note want to list it on PR as well, I think this is almost perfect I did notice that when someone has a status using all 128 chars it will extend the quick profile. Other than that it looked and worked well! 

image

**Comment by InfamousVague** [comment]
I think this is pretty good to add I can work on minor CSS fixes in future fixes. @phillsatellite wanna give it one last look before I do the honors?

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
