### PR TITLE
chore(ui): Font scaling

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖

image
image

Having a bug where the + and - buttons are not working quite as expected.

### CODE REVIEW

**Comment by phillsatellite** [comment]
Few things I found 

.50x

1. The Uplink at the top of the app does not change size 

Screenshot 2023-04-04 at 2 39 43 PM

2. Chats will have a horizontal scroll bar, is this intended? 

Screenshot 2023-04-04 at 2 38 19 PM

3. The emoji's container is smaller but the emoji's remain the same size 

Screenshot 2023-04-04 at 2 36 51 PM

4. The Dev tools could use a little padding in between them

Screenshot 2023-04-04 at 2 40 21 PM

5. The messages attachments will render underneath the chatbar 

Screenshot 2023-04-04 at 2 37 29 PM

6. The release info will render behind the close, minimize, expand tools 

Screenshot 2023-04-04 at 2 35 25 PM

7. UI will break on Friends page when using 1.75x

Screenshot 2023-04-04 at 2 46 20 PM

8. User cannot see the top row of emoji's with 1.75x

Screenshot 2023-04-04 at 2 46 49 PM

**Comment by InfamousVague** [comment]
> Few things I found
> 
> .50x
> 
>     1. The Uplink at the top of the app does not change size
> 
> 
> Screenshot 2023-04-04 at 2 39 43 PM
> 
>     2. Chats will have a horizontal scroll bar, is this intended?
> 
> 
> Screenshot 2023-04-04 at 2 38 19 PM
> 
>     3. The emoji's container is smaller but the emoji's remain the same size
> 
> 
> Screenshot 2023-04-04 at 2 36 51 PM
> 
>     4. The Dev tools could use a little padding in between them
> 
> 
> Screenshot 2023-04-04 at 2 40 21 PM
> 
>     5. The messages attachments will render underneath the chatbar
> 
> 
> Screenshot 2023-04-04 at 2 37 29 PM
> 
>     6. The release info will render behind the close, minimize, expand tools
> 
> 
> Screenshot 2023-04-04 at 2 35 25 PM
> 
>     7. UI will break on Friends page when using 1.75x
> 
> 
> Screenshot 2023-04-04 at 2 46 20 PM
> 
>     8. User cannot see the top row of emoji's with 1.75x


I think for now what we can do is just lower the max font size to 1.5 rem and make the minimum 0.5rem. We cannot change the size of the uplink at the top of the app, that is managed by the OS

**Comment by InfamousVague** [comment]
I tested this as well, only issue I really saw is it takes two clicks for the font scale to update. Additionally the font size does not persist between pages.

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
Good after dev reviews and conflicts resolved

**Comment by sdwoodbury** [comment]
review/changes in progress. 
found a bug that i'm fixing.

**Review by sdwoodbury — APPROVED** [review]
not sure why the storage layout doesn't get an updated font size. but perhaps this can be fixed later.

**Pull request merged**
