### PR TITLE
fix(groups): Fix search crashes

### LINKED ISSUE #1700: bug(groups): group chat search crash
Having a group with special chars in it (e.g. chinese characters) will crash the app when searching.
This is cause we are checking bytes and not chars.
`panicked at common/src/state/mod.rs:1636:18:`

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes crash when searching for groups if a group has chars that are bigger than a byte (usually non latin chars)

### Which issue(s) this PR fixes 🔨

- Resolve #1700

### CODE REVIEW

**Comment by luisecm** [comment]
The following test is failing: 
If you have a group named "Test" that has the user "ChatUserB" (who is a friend also) and then you look for the string "Ch", its only shows the user itself and not the group that has the user as results

image

**Comment by Flemmli97** [comment]
> The following test is failing: If you have a group named "Test" that has the user "ChatUserB" (who is a friend also) and then you look for the string "Ch", its only shows the user itself and not the group that has the user as results
> 
> image

hmm strange. its working for me. can you show the test group?
Screenshot 2024-01-19 at 20 04 56

**Review by stavares843 — CHANGES_REQUESTED** [review]
it crashes using korean chars

안녕하세요

STR:
- go to chat
- create group with name 안녕하세요
- search for it
- crash

crash log from macOS
https://gist.github.com/stavares843/df879ebc26b2c1995008f38a42c23356

crash log from uplink
[19-01-2024_19-27-35.log](https://github.com/Satellite-im/Uplink/files/13993689/19-01-2024_19-27-35.log)

video

https://github.com/Satellite-im/Uplink/assets/29093946/ac9c7884-46b6-48fc-aea2-2f8929d7aaf4

**Comment by stavares843** [comment]
i also noticed that searching using greek or cyrillic does not perform the search

STR:
- go to chat
- add a group with either of these names
Ё Ж З И Й К
Η Θ Ι Κ Λ Μ
- search for the group
- no results

unsure if works on dev because trying the same on dev crashes

Cyrillic Script:
Ё Ж З И Й К

Greek Script:
Η Θ Ι Κ Λ Μ


macOS, m1

**Comment by Flemmli97** [comment]
> it crashes using korean chars
> 
> 안녕하세요
> 
> STR:
> 
> * go to chat
> * create group with name 안녕하세요
> * search for it
> * crash
> 
> crash log from macOS https://gist.github.com/stavares843/df879ebc26b2c1995008f38a42c23356
> 
> crash log from uplink [19-01-2024_19-27-35.log](https://github.com/Satellite-im/Uplink/files/13993689/19-01-2024_19-27-35.log)
> 
> video
> 
>  Gravacao.do.ecra.2024-01-19.as.19.37.27.mov

i am unable to reproduce it. are you sure its on this branch?
as that byte error should be the dev branch which this pr should fix

**Comment by Flemmli97** [comment]
> i also noticed that searching using greek or cyrillic does not perform the search
> 
> STR:
> 
> * go to chat
> * add a group with either of these names
>   Ё Ж З И Й К
>   Η Θ Ι Κ Λ Μ
> * search for the group
> * no results
> 
> unsure if works on dev because trying the same on dev crashes
> 
> Cyrillic Script: Ё Ж З И Й К
> 
> Greek Script: Η Θ Ι Κ Λ Μ
> 
> macOS, m1

was a case sensitiv issue. fixed now

**Comment by luisecm** [comment]
> > The following test is failing: If you have a group named "Test" that has the user "ChatUserB" (who is a friend also) and then you look for the string "Ch", its only shows the user itself and not the group that has the user as results
> > image
> 
> hmm strange. its working for me. can you show the test group? Screenshot 2024-01-19 at 20 04 56

Strange, I see that the test is passing now on last execution, I tested it manually on friday and it worked correctly. I'll keep an eye on the test results for next runs before it's merged and let you know any other findings.

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]

**Pull request merged**
