### PR TITLE
feat(files): disable files/directories that are being deleted

### LINKED ISSUE #1606: feat(files): display something when a file is being deleted
I found that a file may take a second or two to disappear. in that time it may be better if the image was greyed out or had some icon to indicate that the deletion was being performed. 

https://github.com/Satellite-im/Uplink/assets/8636602/d927abdc-eb94-4309-99a0-0a2b0eb04f3a

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Disables files and directories in storage when the user is deleting them. This grays them out till the whole process is completed and the file is gone from the page

### Which issue(s) this PR fixes 🔨

- Resolve #1606

### CODE REVIEW

**Comment by phillsatellite** [comment]
While testing it seemed that even while I was deleting a file I could still click and open up other files

https://github.com/Satellite-im/Uplink/assets/93608357/bd48f76c-c16a-4a0e-8c1e-30060d5d6f47

**Comment by Flemmli97** [comment]
> While testing it seemed that even while I was deleting a file I could still click and open up other files
> 
>  Screen.Recording.2024-03-06.at.12.28.20.PM.mov

shouldnt it be like this? only the file being deleted should be affected imo

**Comment by phillsatellite** [comment]
> > While testing it seemed that even while I was deleting a file I could still click and open up other files
> > Screen.Recording.2024-03-06.at.12.28.20.PM.mov
> 
> shouldnt it be like this? only the file being deleted should be affected imo

Sounds good. I only commented cause I thought by description that user shouldnt be able to click on other files

**Comment by Flemmli97** [comment]
removed change request label now as im assuming its fine atm?

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
