### PR TITLE
fix(chat): Dont stop profile fetching when one errors

### LINKED ISSUE #1934: bug(chat): custom profile picture will be missing when adding friends
**Issue:**
If you add someone and they already changed their profile picture before adding you, you will not see it until they update it again. 

**OS:**
All

**Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Makes it so when banner/profile errors during fetching the whole thing is not aborted. This MIGHT fix the linked issue where one person changes their profile picture, another tries to add them but only sees a blank profile picture.
  I was only able to reproduce the linked issue once (might be due to some caching thing maybe?) so not really able to confirm this but it seemed to be a good point here.
  
### Which issue(s) this PR fixes 🔨

- Resolve #1934

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2024-04-17, às 16 37 30


i know you mentioned it "might fix" the issue but just to let you know that still has some blank avatars on this branch

macOS, m1

**Comment by phillsatellite** [comment]
I also had Windows account update their picture and as soon as they did it appeared grey for MacOS user 
image

Screenshot 2024-04-17 at 11 42 21 AM

**Comment by Flemmli97** [comment]
can you post the logs during it?

**Comment by stavares843** [comment]
```

sara@MBP-PRO-M1-Sara Uplink % cargo run
   Compiling uplink v1.0.2 (/Users/sara/Uplink/ui)
    Finished dev [unoptimized] target(s) in 14.49s
     Running `target/debug/uplink`
2024-04-17 18:26:55 | DEBUG | starting uplink
2024-04-17 18:26:55 | DEBUG | warp initialization
2024-04-17 18:26:55 | DEBUG | add_to_themes: /Users/sara/.uplink/themes
2024-04-17 18:26:55 | DEBUG | add_to_themes: ui/extra/themes
2024-04-17 18:26:55 | DEBUG | shuttle addresses: ["/ip4/159.65.41.31/tcp/8848/p2p/12D3KooWRF2bz3KDRPvBs1FASRDRk7BfdYc1RUcfwKsz7UBEu7mL"]
2024-04-17 18:26:55 | DEBUG | starting automute
2024-04-17 18:26:55 | DEBUG | starting automute helper
2024-04-17 18:26:55 | DEBUG | add_to_themes: /Users/sara/.uplink/themes
2024-04-17 18:26:55 | DEBUG | add_to_themes: ui/extra/themes
2024-04-17 18:26:55 | DEBUG | add_to_themes: /Users/sara/.uplink/themes
2024-04-17 18:26:55 | DEBUG | add_to_themes: ui/extra/themes
2024-04-17 18:26:55 | DEBUG | received warp cmd: Tesseract { AccountExists } 
2024-04-17 18:26:55 | DEBUG | account_exists: true
2024-04-17 18:26:58 | DEBUG | received warp cmd: MultiPass { TryLogIn } 
2024-04-17 18:26:58 | DEBUG | add_to_themes: /Users/sara/.uplink/themes
2024-04-17 18:26:58 | DEBUG | add_to_themes: ui/extra/themes
2024-04-17 18:26:58 | DEBUG | warp_runner::manager::run
2024-04-17 18:26:58 | DEBUG | state::mutate: SidebarHidden: true
2024-04-17 18:26:58 | DEBUG | add_to_themes: /Users/sara/.uplink/themes
2024-04-17 18:26:58 | DEBUG | add_to_themes: ui/extra/themes
2024-04-17 18:26:58 | DEBUG | state::mutate: RegisterExtensions
2024-04-17 18:26:58 | DEBUG | Loaded 0 extensions.
2024-04-17 18:26:58 | DEBUG | WARP CMD: RayGun { InitializeWarp } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2024-04-17 18:26:58 | DEBUG | Updating directories opened to browse
2024-04-17 18:26:58 | INFO | Get items from current directory worked!
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: RayGun { FetchMessages } 
2024-04-17 18:26:58 | DEBUG | init_chat_data
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:58 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:26:59 | DEBUG | use_effect for init_msg_scroll 9eaeed37-3c38-d90c-5abb-655680ebe018
2024-04-17 18:27:08 | DEBUG | received multipass event: IdentityOnline { did: did:key:z6Mku7poUPEPmD6eXBrodVMp7ESCRbg67mDbkZ4LAqBjYxfy }
2024-04-17 18:27:08 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:08 | DEBUG | process_warp_event: MultiPassEvent { FriendOnline } 
2024-04-17 18:27:08 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:12 | DEBUG | received multipass event: IdentityUpdate { did: did:key:z6Mku7poUPEPmD6eXBrodVMp7ESCRbg67mDbkZ4LAqBjYxfy }
2024-04-17 18:27:12 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:12 | DEBUG | process_warp_event: MultiPassEvent { IdentityUpdate } 
2024-04-17 18:27:12 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:16 | DEBUG | received multipass event: IdentityUpdate { did: did:key:z6Mku7poUPEPmD6eXBrodVMp7ESCRbg67mDbkZ4LAqBjYxfy }
2024-04-17 18:27:16 | DEBUG | process_warp_event: MultiPassEvent { IdentityUpdate } 
2024-04-17 18:27:16 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:16 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:17 | DEBUG | received multipass event: IdentityUpdate { did: did:key:z6Mku7poUPEPmD6eXBrodVMp7ESCRbg67mDbkZ4LAqBjYxfy }
2024-04-17 18:27:17 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
2024-04-17 18:27:17 | DEBUG | process_warp_event: MultiPassEvent { IdentityUpdate } 
2024-04-17 18:27:17 | DEBUG | WARP CMD: MultiPass { UpdateProfilePicture } 
```


you want any specific flag?

**Comment by Flemmli97** [comment]
i think errors are on by default anyways right? if so no

**Comment by stavares843** [comment]
i believe so yes

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
