### PR TITLE
update(Thumbnail): Thumb without external libraries

### LINKED ISSUE #21: chore(files): Change code from video and pdf thumbnail
Instead of use commands, change the code to use crates from rust, it save memory and space for the app

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Updated the code, to just use crates and not necessary more external libraries to upload thumbnails for pdf files 
a. External libraries can let app with bigger size and can affect performance
b. Video thumbs will keep ffmpeg lib for now

- 

### Which issue(s) this PR fixes 🔨

- Resolve Satellite-im/Uplink-Backlog#21

### CODE REVIEW

**Comment by dariusc93** [comment]
Is there any reason not to use `image` crate for thumbnails for media files?

**Comment by sdwoodbury** [comment]
The image crate looks a lot more mature. 3700 stars on Github vs 5 for thumbnailer. 
https://github.com/image-rs/image
https://github.com/Trivernis/thumbnailer

Also, please make the Cargo workflow pass. `cargo clippy --fix` would probably fix most of it for you. 

image

**Comment by lgmarchi** [comment]
> Is there any reason not to use `image` crate for thumbnails for media files?

When you say media, is images and video files?

**Comment by dariusc93** [comment]
> > Is there any reason not to use `image` crate for thumbnails for media files?
> 
> When you say media, is images and video files?

That is correct. Looking at the dependency used, it looks like they also use `image` for producing thumbnails too (would have to double check though)

**Comment by lgmarchi** [comment]
> > > Is there any reason not to use `image` crate for thumbnails for media files?
> > 
> > 
> > When you say media, is images and video files?
> 
> That is correct. Looking at the dependency used, it looks like they also use `image` for producing thumbnails too (would have to double check though)

For video files, I didn't find any other solution without using ffmpeg, so I will back ffmpeg lib for it 

thumbnailer, inside crate, is using ffmpeg lib as well to make thumb from videos

**Comment by phillsatellite** [comment]
Hello my friend, so far on MacOS preview opened to a black screen 

MacOS

https://user-images.githubusercontent.com/93608357/227622394-c09258ee-f73c-46e1-b2ee-63f11d496bc7.mov

Windows- 

https://user-images.githubusercontent.com/93608357/227622450-b5b7b85b-bec6-4f28-abaf-7fcbf21a60bc.mp4

**Comment by phillsatellite** [comment]
Sent Lucas a DM I had tried building but got this error thrown at me, he said he already knows the fix 💥 

Screenshot 2023-03-28 at 1 01 06 PM

**Comment by phillsatellite** [comment]
So I pulled latest changes and error was gone, but I did have @InfamousVague and @WanderingHogan both test with me and neither of us could get the thumbnail to appear with PDF or MOV (verified we have ffmeg installed

**Comment by WanderingHogan** [comment]
With the release coming up we are going to close this, and come back to it after we make the public builds.

**Pull request closed without merging**
