### PR TITLE
chore(directories): rename uplink directory

### LINKED ISSUE #320: Settings - Themes dropdown is missing
**Issue:** The themes dropdown list does not appear when you click it. This is from https://github.com/Satellite-im/Uplink/pull/274

**OS:**
Windows
MacOS

Screenshot 2023-02-21 at 4 52 02 PM

_Originally posted by @phillsatellite in https://github.com/Satellite-im/Uplink/issues/274#issuecomment-1439147914_

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- uplink has an application directory called `.uplink`. this PR renames a folder within that directory. 
- tested on Linux and Mac, and  couldn't replicate #320
- the rational behind renaming `.uplink/uplink` to `.uplink/.user` (at least adding the leading `.` to hide the file) is that this directory, which contains `state.json` and the `warp` folder, isn't meant to be modified by the user, while `.uplink/extensions` and `.uplink/themes` expect user interaction. 

### Which issue(s) this PR fixes 🔨

- Resolve #320

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Stu! Worked perfect on MacOS but still not getting the themes dropdown on Windows I tried cargo update/doing a new account and still no luck 


https://user-images.githubusercontent.com/93608357/221046039-26c55d23-4e18-4e89-ab3a-d2a807ee1024.mp4

**Review by lgmarchi — CHANGES_REQUESTED** [review]
I don't know if is correct, but warp and state are inside .user yet.
image


I had same problem as @phillsatellite on windows.

**Comment by sdwoodbury** [comment]
@phillsatellite  

not having the themes dropdown populated, except with `Default` isn't always a bug. see this:

image


running `ui` from a directory besides the root of the `uplink` repository could cause `themes` to not be populated.   

what does your `~/.uplink` directory look like? if there's no `themes` folder here, then i think the picture you showed isn't a bug. also, if you manually copy the contents of `ui/extra/themes` into `.uplink/themes`, does the dropdown populate?

**Comment by sdwoodbury** [comment]
@phillsatellite  @luisecm  I think the commit [c060136](https://github.com/Satellite-im/Uplink/pull/338/commits/c060136f7731f397842872637584a9a5aa653c76) should fix any issues. turns out `themes` was being copied to `uplink_path` instead of `themes_path`.

**Review by phillsatellite — APPROVED** [review]

**Comment by tooshel** [comment]
> @phillsatellite @luisecm I think the commit [c060136](https://github.com/Satellite-im/Uplink/pull/338/commits/c060136f7731f397842872637584a9a5aa653c76) should fix any issues. turns out `themes` was being copied to `uplink_path` instead of `themes_path`.

themes_path is new and went in after we had working themes . . . I bet at some point it just copied the themes folder to the uplink_path and that copy is what made the themes_path in the first place. I wonder if there could be a race condition where the themes folder does exist. Can you delete the themes folder and that folder and the themes are copied back?

**Review by dariusc93 — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]

**Comment by sdwoodbury** [comment]
> > @phillsatellite @luisecm I think the commit [c060136](https://github.com/Satellite-im/Uplink/pull/338/commits/c060136f7731f397842872637584a9a5aa653c76) should fix any issues. turns out `themes` was being copied to `uplink_path` instead of `themes_path`.
> 
> themes_path is new and went in after we had working themes . . . I bet at some point it just copied the themes folder to the uplink_path and that copy is what made the themes_path in the first place. I wonder if there could be a race condition where the themes folder does exist. Can you delete the themes folder and that folder and the themes are copied back?

there could be a "race" between the user and `ui` when starting `ui` if the `themes` dir (from the codebase, not the one from `~/.uplink`) is deleted by the user. it doesn't seem like this is a  problem though.

**Pull request merged**
