### PR TITLE
fix(attachment): show thumbnail for images

### LINKED ISSUE #1400: bug(chat): Thumbnails missing when sending files
**Issue:**
When a user sends files from "browse Uplink files" the thumbnails will be missing.

**STR:**
- Go to chat 
- Click + and then _Browse Files_
- Select files to send 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/664ab14e-7052-4e24-9bae-ead2ba26cdf7

### LINKED ISSUE #1419: crash(chat): Crash when dragging multiple files into chat
**Issue:**
When you try to drag mutiple files in chat to send as soon as you hover over app, it will crash 

**OS:**
Windows 
MacOS
Linux

**Crash log:**

[26-10-2023_12-07-20.log](https://github.com/Satellite-im/Uplink/files/13179919/26-10-2023_12-07-20.log)

```2023-10-26 12:10:32 | DEBUG | received multipass event: IdentityOnline { did: did:key:z6MkpZzNZsmduPW8acLZ9YhtRRemU3TNtGiQQUfzZg5eWeUJ }
2023-10-26 12:10:32 | DEBUG | process_warp_event: MultiPassEvent { FriendOnline } 
2023-10-26 12:11:47 | INFO | Drag Event: Hovered { paths: ["/var/folders/by/c33qyq0x0fg5jgxyzk1h64kr0000gn/T/TemporaryItems/NSIRD_screencaptureui_1SXCar/Screenshot 2023-10-26 at 12.11.44\u{202f}PM.png"], position: PhysicalPosition { x: 1893.0078125, y: 395.0390625 } }
2023-10-26 12:11:47 | INFO | Drag Event: Cancelled
2023-10-26 12:11:47 | DEBUG | state::mutate: SetChatAttachments
2023-10-26 12:11:49 | INFO | Drag Event: Hovered { paths: ["/Users/phillwisniewski/Desktop/26-10-2023_12-07-20.log", "/Users/phillwisniewski/Desktop/Screenshot 2023-10-26 at 12.11.44\u{202f}PM.png"], position: PhysicalPosition { x: 1829.0703125, y: 18.5703125 } }

The crash has been saved to /Users/phillwisniewski/.uplink/crash-logs/26-10-2023_12-11-49.log
```

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/cca7fa47-159f-4bd8-acdb-bb724665333a

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- shows thumbnails for images attached from constellation. 
- and fix a misuse of get_local_text - if it has an arg, this will crash. 
- improves `get_local_text_with_args` - made the function  generic so that you don't have to type `.into()` every time. See here: `common/src/language/mod.rs`

### Which issue(s) this PR fixes 🔨

- Resolve #1400 
- Resolve #1419

### CODE REVIEW

**Comment by phillsatellite** [comment]
Getting this error when trying to compile on Mac Linux or Windows

Screenshot 2023-10-27 at 3 32 57 PM

**Comment by phillsatellite** [comment]
Just noticed a small thing on my Linux VM, I wasn't able to drag and drop any files into chat 

https://github.com/Satellite-im/Uplink/assets/93608357/19086b34-4018-4440-a1e1-cd858b3ebd32

**Comment by sdwoodbury** [comment]
@phillsatellite  cannot reproduce on a physical device. edit: but i'll look into what could be done about the event being cancelled.

**Comment by sdwoodbury** [comment]
@phillsatellite  I found a bunch of problems related to the file drop handler. the issue you flagged isn't caused by this PR - it's a separate bug.

**Comment by sdwoodbury** [comment]
I opened a new ticket for the drop handler https://github.com/Satellite-im/Uplink/issues/1437

**Review by dariusc93 — APPROVED** [review]

**Comment by phillsatellite** [comment]
So I tested with both @stavares843 and @WanderingHogan when I tested with Sara she sent me a .png and it worked great. When I tested with Hogan he sent me a .jpeg and it wouldnt ever download it would just save as 0bytes. Everything else on the PR worked great so I'm thinking this can get approved and we can re open this ticket here https://github.com/Satellite-im/Uplink/issues/1262 @stavares843 what do you think?

**Comment by stavares843** [comment]
i agree 🔨

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
