### PR TITLE
task(groups): Group chat UI refactor

### LINKED ISSUE #1608: task(groups): Add ability to let other users add friends to the group
**Task:**
- [ ] **Ability to let group members add new users to the group:** - Pretty much like the title says, we want to offer the Group Creator a toggle, when toggle is on it allows other members of the group to have the ability to add new users into the GroupChat

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖
WIP

- [x] Create / make associated group chat UI changes.
- [x] Add settings page in UI for group.
- [x] Relocate group member modification into it's own thing.
- [x] Add context menu for additional options.
- [x] Create bindings in warp-runner for new group feature(s).
- [x] Bind warp runner features to new UI.

### CODE REVIEW

**Comment by luisecm** [comment]
App is failing on compile process:

image

**Comment by InfamousVague** [comment]
> App is failing on compile process:
> 
> image

There is a change in warp that caused this, working on this now.

**Comment by luisecm** [comment]
Looks like there is a bug caught by the tests. If you log out from the app, and then login again, the conversations disappear from Sidebar. 

A chat replies test is failing on this PR after the user is logging back to the app and the app is showing the Welcome Screen instead of the last chat conversation. The test is trying to open the context menu from last message received, since the conversation is not displayed, the "elementId" not found error is shown on logs
image

**Comment by InfamousVague** [comment]
> Looks like there is a bug caught by the tests. If you log out from the app, and then login again, the conversations disappear from Sidebar.
> 
> A chat replies test is failing on this PR after the user is logging back to the app and the app is showing the Welcome Screen instead of the last chat conversation. The test is trying to open the context menu from last message received, since the conversation is not displayed, the "elementId" not found error is shown on logs image

This is almost certainly related to the changes in warp recently and not this branch specifically. Since this branch uses a newer version of Warp than dev presumably we'd see new bugs here first.

**Comment by luisecm** [comment]
Strange bug is happening with non-group chat conversations:
- Conversation is not loaded and context menu for that chat on sidebar fails to perform "Delete chat" action

https://github.com/Satellite-im/Uplink/assets/35935591/3d5d0ab9-4e59-4f33-9983-922a9ef0a209

This is why the following automated test is failing:
image

**Comment by dariusc93** [comment]
Just as a note, this PR should be merged after https://github.com/Satellite-im/Uplink/pull/1839 has been merged

**Comment by phillsatellite** [comment]
Found a few things to note while testing: 

1. Looks like there isnt a way to back out of renaming the group. When this happens the user is able to switch to other chats (even 1on1 chats where this shouldnt be possible) and rename them 

https://github.com/Satellite-im/Uplink/assets/93608357/27997a70-9b49-4fd7-8ddf-d528d946e81b

2. Not sure if this is intended or not but even when letting others rename or add to group is toggled off, other members are still able to bring up the Settings for Groups

https://github.com/Satellite-im/Uplink/assets/93608357/ca4bac9a-3ed9-4425-bcfe-408496e812a0

3. Noticed I was getting a crash when toggling on the group settings. I think this was due to the fact that one of the other users had both group settings toggled on momentarily 

https://github.com/Satellite-im/Uplink/assets/93608357/4d8f8630-3c42-42ca-b624-2e940e7f97a8

[12-02-2024_14-00-04.log](https://github.com/Satellite-im/Uplink/files/14249327/12-02-2024_14-00-04.log)

**Comment by InfamousVague** [comment]
image

Added a button to cancel editing the group name. This doesn't actually fix the ability to leave the rename up and change to another chat, I'll look into this in another push tomorrow hopefully.

**Edit:** This should be fixed now too, actually.

**Comment by InfamousVague** [comment]
issue 1 and 2 mentioned by @phillsatellite should be good to go now.

**Comment by zeenix** [comment]
> 3. Noticed I was getting a crash when toggling on the group settings. I think this was due to the fact that one of the other users had both group settings toggled on momentarily

@phillsatellite I'm unable to reproduce this. In fact, the settings dialog disappears immediately after I switch the toggle so I can quickly toggle back and forth, like you're doing in the screencast.

**Comment by InfamousVague** [comment]
It disappearing right after changing may be because I added the code to
close it after changing metadata. If this is undesirable we might have to
modify it and move the code to only close the modals when changing routes

**Comment by stavares843** [comment]
| #   | Description                                                                                            | Log File                                                                                         | Screenshot/Video                                                                                                          |
| --- | ------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------- |
| 1   | App crashed when creating a group with only Phil and I, activating second toggle in group settings | [13-02-2024_17-50-09.log](https://github.com/Satellite-im/Uplink/files/14270320/13-02-2024_17-50-09.log) | N/A                                                                                                                         |
| 2   | App crashed when removing the first toggle in the same group                                          | [13-02-2024_17-51-14.log](https://github.com/Satellite-im/Uplink/files/14270325/13-02-2024_17-51-14.log) | N/A                                                                                                                         |
| 3   | "Close chat" option in group top bar doesn't close chat, not present in dev                            | N/A                                                                                              | Close Chat Option        |
| 4   | Both context menus appear when right-clicking on group name                                            | N/A                                                                                              |  [Video](https://github.com/Satellite-im/Uplink/assets/29093946/24e62d79-eb6f-442c-bea3-6ab781ed1360)              |
| 5   | Cursor doesn't focus and "X" icon is cut off when renaming group                                      | N/A                                                                                              | Rename Group Issue        |

macOS, m1

**Comment by phillsatellite** [comment]
I also get both crashes that @stavares843 had mentioned above

**Comment by stavares843** [comment]
crashes are fixed 🎉

**Comment by stavares843** [comment]
Updated list

We can fix this in other PR if you prefer

let us know and we can add tickets for it 🔨 



| #   | Issue Description                                                                                            | Screenshot/Video                                                                                                |
| --- | ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------- |
| 1.  | When you are not the group creator, right click on the group name displays a blank context menu                           | Screenshot                  |
| 2.  | If you create the group, give permissions to other user to add/remove users, he cant remove the group creator and returns the following error in the terminal: `Public key is invalid` | image                  |
| 3.  | If you are renaming the group doing right click renders the context menu behind the input field                | Screenshot                  |
| 4.  | Cursor doesn't focus and "X" icon is cut off when renaming group                                             | Screenshot                                                                             |

**Comment by zeenix** [comment]
> When you are not the group creator, right click on the group name displays a blank context menu

This is already split: #1847.

> let us know and we can add tickets for it 🔨

I guess this is for @InfamousVague but I had an understanding with him that we can fix some of the issues afterwards, so please let's proceed with this approach.

**Comment by stavares843** [comment]
thanks for clarifying 🔨

**Comment by InfamousVague** [comment]
> When you are not the group creator, right click on the group name displays a blank context menu
 
For this we can either not display the context menu when there is no items, or we can add "view members" to the context menu to simply trigger the popup to view the members of the group instead of managing the members so it's never empty.

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
