### PR TITLE
chore(ci): adds a workflow to build linux in every PR

### PR DESCRIPTION
**Pull request by stavares843**
### What this PR does 📖

- Adds a workflow to build linux in every PR to make sure it builds properly in each PR in Linux

image

### CODE REVIEW

**Review by WanderingHogan — CHANGES_REQUESTED** [review]
Is it possible to use something like this: https://github.com/marketplace/actions/toml-reader to pull the toolchain value from cargo.toml?

**Comment by sdwoodbury** [comment]
the cargo workflow runs/builds on linux already. Clippy will fail if the project won't compile. i believe this workflow is redundant.

**Comment by luisecm** [comment]
> the cargo workflow runs/builds on linux already. Clippy will fail if the project won't compile. i believe this workflow is redundant.

This means that the job that builds linux on automated tests is redundant too. I added this job recently just to ensure that app builds correctly on Linux. Since there are no automated tests for linux yet, I will add a PR to remove my build linux job too

**Comment by stavares843** [comment]
got it, thanks! 🔨

**Pull request closed without merging**
