### PR TITLE
fix(textarea): add onblur to textarea to fix click out of edit

### LINKED ISSUE #396: Chat - Add ability to click out of Edit message
**Task:** Another thing from #380 we wanted to ad the ability for the User to just click out of of focus of Edit message to exit

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- add onblur to textarea to fix click out of edit

### Which issue(s) this PR fixes 🔨

- Resolve #396

### CODE REVIEW

**Review by sdwoodbury — DISMISSED** [review]

**Comment by phillsatellite** [comment]
Yo! This works awesome, I do have one question otherwise all good for me! 

With this PR the user is able to click out of replying to a message and that message will send. Is that expected? My only concern was there are a lot of times I'm replying to User B and then while doing that I have User C message me and I will switch to that User C chat before Im actually finished my message I was typing out to User B. But that might be a personal thing though. I also think it would be cool to eventually label a message edited after it is saved 

https://user-images.githubusercontent.com/93608357/224430282-eba04ee2-6b0f-4254-9449-64c0cb0ac31a.mov

**Comment by Jekrimo** [comment]
> Yo! This works awesome, I do have one question otherwise all good for me!
> 
> With this PR the user is able to click out of replying to a message and that message will send. Is that expected? My only concern was there are a lot of times I'm replying to User B and then while doing that I have User C message me and I will switch to that User C chat before Im actually finished my message I was typing out to User B. But that might be a personal thing though. I also think it would be cool to eventually label a message edited after it is saved

This is such a good point dude, let me make some changes

**Comment by phillsatellite** [comment]
Just needs to have the fix for the replies that I mentioned above and will be good to merge 😄 

https://user-images.githubusercontent.com/93608357/225375034-cf5a60ac-bdfa-43fb-92b1-137e9c9f5d36.mov

**Comment by phillsatellite** [comment]
> Just needs to have the fix for the replies that I mentioned above and will be good to merge 😄

https://user-images.githubusercontent.com/93608357/225374922-9dda6e88-b2f7-40db-a82d-1fc5e4e1c455.mov

**Review by phillsatellite — DISMISSED** [review]

**Review by sdwoodbury — APPROVED** [review]

**Pull request merged**
