### PR TITLE
fix(files): Fix path decoding issue on linux for file dragging

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes the file verification for drag and drop not taking decoding into consideration. Noticeable on linux when you try to e.g. drag and drop a file with whitespace.

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]
this looks good. @lgmarchi is re-writing the storage layout and this could cause a merge conflict. Please double check with him before merging.

**Comment by phillsatellite** [comment]
Hey @Flemmli97 quick question, in this PR on MacOS and Windows I can drag file into chat or drag and drop file onto the files page but on Linux doesn't seem to be working



https://github.com/Satellite-im/Uplink/assets/93608357/659e7507-b404-47a2-8a6a-7a9b9df6e802

**Comment by Flemmli97** [comment]
> Hey @Flemmli97 quick question, in this PR on MacOS and Windows I can drag file into chat or drag and drop file onto the files page but on Linux doesn't seem to be working
> 
>  Screen.Recording.2023-06-09.at.11.38.15.AM.mov

hmm this doesnt seem to happen on my end. drag and drop works for me on linux. your not on a vm right?

**Review by dariusc93 — APPROVED** [review]

**Comment by stavares843** [comment]
hogan tested in a real linux and works as well

**Pull request merged**
