### PR TITLE
fix(scrolling): handle edge cases when scrolling

### LINKED ISSUE #1318: bug(scroll to bottom): button doesn't always disappear
documented here: https://github.com/Satellite-im/Uplink/pull/1307

### LINKED ISSUE #1566: task(chat): Incoming messages should not affect scroll
**Task:**
- [ ] While scrolling up and reading higher messages in the chat, if any incoming messages are received the scroll position should not be affected and keep its place. The button Scroll to Bottom should say New Message Below when new message is received 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/8eb15bc3-43d3-4209-a768-761d6817c5a2

### LINKED ISSUE #1576: bug(chats): chats is broken
the scroll button doesn't appear when it should (it will eventually appear)
when you scroll up and receive a message, it isn't displayed when you scroll down again. using the scroll button (when it eventually appears) doesn't help. 

https://github.com/Satellite-im/Uplink/assets/8636602/761cc9ee-43cb-4b0c-9484-c151d989d229

### PR DESCRIPTION
**Pull request by sdwoodbury**
#### Bugs Fixed
- scroll button didn't appear when scrolling up past a single line message
- if the most recent X messages were all from the same sender and you scrolled down and fetched more messages, and some of that X was supposed to be in the bottom of the view, the page would scroll to most recent because `scroll-to-bottom` didn't scroll the given message into view but instead the `time-ago` element (which could be quite far below the desired message).
- if the user scrolls up but is still on the first page of messages and a new message is received, you no longer are force scrolled to the most recent message. 

The above was accomplished by altering `view_init.scroll_to` within the `onscroll` event handler in `messages/mod.rs`, and by adding a field to `ChatBehavior` to indicate that a message has been received while the user had scrolled up. Also the logic for `JsMsg::Add` and `JsMsg::Remove` was modified to set and clear the scroll button, but only after all the messages in the page had been processed by the IntersectionObserver. 

### Which issue(s) this PR fixes 🔨

- Resolve #1576 
- Resolve #1566 
- Resolve #1318

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
While testing, we have noticed that when you go to pinned messages > go to pinned message > the scroll to bottom bar does not appear

https://github.com/Satellite-im/Uplink/assets/29093946/0836cfed-416f-45f4-87b0-d733df50c2c3

the same flow works in dev

https://github.com/Satellite-im/Uplink/assets/29093946/cce4fb76-1da1-401f-9e7c-174adc1413f6


macOS 13.6

**Review by stavares843 — CHANGES_REQUESTED** [review]
When we scroll everything to the bottom > upload image > browse file > add a image > the scroll to bottom appears again even though there's nothing to scroll there


https://github.com/Satellite-im/Uplink/assets/29093946/f56c704d-b213-423f-9ef9-102f93c07052

the same flow works fine in dev

https://github.com/Satellite-im/Uplink/assets/29093946/b8cbb492-1ff1-40ac-ae2b-97794a986a9c

macOS 13.6

**Comment by sdwoodbury** [comment]
@stavares843  ~~it's ready for testing again.~~ nvm

**Review by stavares843 — CHANGES_REQUESTED** [review]
on dev when you go to pinned messages > go to > after scroll the box is dismissed as expected

https://github.com/Satellite-im/Uplink/assets/29093946/cce4fb76-1da1-401f-9e7c-174adc1413f6


but on this branch is not now with the latest commits that is

https://github.com/Satellite-im/Uplink/assets/29093946/3ce943c3-7ff8-448f-8137-576878566632







macOS 13.6

**Comment by stavares843** [comment]
also when you scroll a bit and the scroll to bottom appears, now at least on my mac is way slower but phil doesnt have that issue


https://github.com/Satellite-im/Uplink/assets/29093946/7ca595d9-852d-4ddf-9343-8b8c81eb7347

macOS 13.6

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://github.com/Satellite-im/Uplink/assets/29093946/f15432a2-819c-4ef4-b521-1686997773de

when sending a image, you scroll > appears the scroll to bottom and then it auto scrolls to the top by itself

that scroll you are seeing in the video is the app itself

macOS 13.6

**Review by stavares843 — CHANGES_REQUESTED** [review]
when you send a image > scroll > appears the scroll to bottom > delete image > it will show the following glitch

https://github.com/Satellite-im/Uplink/assets/29093946/0d0eb283-96e8-4dd9-8e01-21cc8d96b80e

macOS 13.6

**Comment by sdwoodbury** [comment]
@Sara shouldn't be able to reproduce the issue anymore on a Mac :grin: but for a bad reason :(

**Review by stavares843 — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
