### PR TITLE
fix(messages): fix long strings breaking ui

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

Issue: If user sends a long message in chat, it will break the UI and let user scroll horizontally in the sidebar and chat

### Which issue(s) this PR fixes 🔨

#197

### CODE REVIEW

**Comment by phillsatellite** [comment]
Added Do not Merge since its not completely reviewed yet

**Review by dariusc93 — DISMISSED** [review]

**Comment by phillsatellite** [comment]
Tested on Mac and Windows: The chat will be fixed if a long message is sent 🎉  but I did still have issues with being able to scroll horizontally in the Sider and both MacOS and WindowsOS 

https://user-images.githubusercontent.com/93608357/218169621-f35f6de1-c432-42ba-971c-14493376acc6.mov

**Comment by Jekrimo** [comment]
fixed! Such a weird css prop I found.

**Comment by tooshel** [comment]
> fixed! Such a weird css prop I found.

I've never seen that before either! I had to look it up for my own sanity.  https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

**Comment by Jekrimo** [comment]
> > 
> 
> I've never seen that before either! I had to look it up for my own sanity. [https://developer.mozilla.org/en-](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)

it doesn't even register correctly in the editor, it's crazy. Took days to find but I'll never forget it now damn

**Review by lgmarchi — APPROVED** [review]
Tested on MacOS: 
image

And Windows: 
image

Working fine! Approved!

**Comment by phillsatellite** [comment]
Perfecto! 🤌 Fixed on MacOS and Windows in Desktop and Mobile view 😄  1 more Dev review and this is ready to merge

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
