### PR TITLE
fix(File): Doesn't show warning when rename file name to same name

### LINKED ISSUE #983: bug(files): if you try to rename the same file the same name returns error
STR:
- go to files
- add a file
- rename to ''test''
- save
- works fine
- rename again the same file to ''test''
- says there is already a file with that name

https://github.com/Satellite-im/Uplink/assets/29093946/a7b57494-aaaa-4316-86e0-65c284a83d81

macOS

### PR DESCRIPTION
**Pull request by lgmarchi**
#### 1. Doesn't show warning when rename file name to same name

https://github.com/Satellite-im/Uplink/assets/63157656/aa551775-ac60-444f-967c-c07fee131834

### Which issue(s) this PR fixes 🔨

- Resolve #983

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]
works great! 🎉 


we also need to fix for the folders, do you want a ticket for that to fix separately or you wanna address that here as well?

**Comment by lgmarchi** [comment]
> works great! 🎉
> 
> we also need to fix for the folders, do you want a ticket for that to fix separately or you wanna address that here as well?

I think we can address here as well, small changes. Just a minute

**Comment by stavares843** [comment]
neat, thanks! 🎉

**Comment by lgmarchi** [comment]
Done.

**Review by stavares843 — APPROVED** [review]

**Comment by sdwoodbury** [comment]
what happens if a file is given the same name as a folder (and vice versa)? Allowing that could be problematic

**Comment by lgmarchi** [comment]
> what happens if a file is given the same name as a folder (and vice versa)? Allowing that could be problematic

It is allowed. Even with files, we can have test.mp4 and test.txt, it will not be a problem. And folder and files are like different types.

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
