### PR TITLE
feat(chat): Remember chat scrolls

### LINKED ISSUE #1020: feat(chats): remember scroll position when someone scrolls up
I think Uplink needs to be able have the user scroll up in a chat, switch conversations/pages, and then return to that conversation and be at the same spot. 

Receiving a new message shouldn't necessarily make the conversation jump to the bottom. 

It might be nice to have a button (that appears after scrolling up) that scrolls to the bottom of the conversation.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Remembers the current position in chat and goes to that position when user switches back to that chat
- If a user goes to a new chat with unread messages goes to the top of unread messages
- If a user scrolls up the chat a certain amount a button will appear to scroll all the way back down again

### Which issue(s) this PR fixes 🔨

- Resolve #1020

### CODE REVIEW

**Comment by lgmarchi** [comment]
**System tested: MacOS, m1**

@Flemmli97 When I scrolled all chat to the top, has some weird effect:

https://github.com/Satellite-im/Uplink/assets/63157656/f8896f29-030e-453d-a4d4-a484ade314d3

Other thing, the button to scroll to bottom, does not work some times: 

https://github.com/Satellite-im/Uplink/assets/63157656/3b7293e9-e3b6-4917-bb95-955fa78d7662

Other behavior, sometimes scroll changes automatically as well: 

https://github.com/Satellite-im/Uplink/assets/63157656/a5788a3a-c0d6-47a4-bc00-1a33b0fb22e8

When we attach file, it overlap scroll to bottom button: 

image


I was able just to replicate one time, but I think it is good to let here: 

image

Mentioning @phillsatellite and @stavares843 here, to see if they can replicate these problems as well.

This PR is really nice, but need some changes yet.

**Comment by sdwoodbury** [comment]
looks like scroll to bottom actually scrolls to the beginning of the conversation, not the end.

**Comment by stavares843** [comment]
Captura de ecrã 2023-08-04, às 22 31 01


missing linter 🔨

**Review by InfamousVague — APPROVED** [review]

**Comment by InfamousVague** [comment]
Code looks good after linter + merge conflict

**Comment by Flemmli97** [comment]
waiting for dioxus 0.4 for some changes

**Comment by dariusc93** [comment]
Changing to draft until #1081 is complete

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/pull/1081 was merged 🎉

**Comment by Flemmli97** [comment]
idk how to remove that draft indicator but its not a draft anymore

**Review by sdwoodbury — CHANGES_REQUESTED** [review]
it looks like there's a duplicate `use_effect` there

image

Also, it looks like the `use_effect` on line 202 is also intended to do the same thing. Is the call to `../scroll_to_message.js` still needed? 
image

**Comment by Flemmli97** [comment]
oh. might be cause the merge...

**Comment by Flemmli97** [comment]
> it looks like there's a duplicate `use_effect` there
> 
> image
> 
> Also, it looks like the `use_effect` on line 202 is also intended to do the same thing. Is the call to `../scroll_to_message.js` still needed? image

they actually do two different things.
the first is from the pinning message pr that handles scrolling to a specific message. 
the second is for this component alone

**Review by sdwoodbury — APPROVED** [review]

**Pull request merged**
