### PR TITLE
fix(javascript): fix javascript errors

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- there were lots of javascript errors due to trying to add event listeners on objects which were either 'null' or 'undefined'. 
- add checks to prevent this
- remove a nested button - it used to be that if a Button had an icon, an IconButton would be rendered inside of a Button. 
- change tooltip logic for buttons to not use javascript
- remove tooltip for textarea. this affects the Chatbar. instead, display a message in the chatbar when it is disabled
image

after change: 
image

before change: 
image

### Which issue(s) this PR fixes 🔨

- Resolve #

### CODE REVIEW

**Comment by WanderingHogan** [comment]
Screenshot 2023-04-21 at 8 42 53 AM
more red than green is a beautiful thing

**Comment by phillsatellite** [comment]
Hey Stu only one very minor issue I could find, when you hover over the chat input on Windows a tooltip appears saying "you are not friends anymore" even if user had just added them. 

https://user-images.githubusercontent.com/93608357/233688338-0bff293d-a460-44a5-bab5-a06f25cffcd0.mp4

**Comment by sdwoodbury** [comment]
> Hey Stu only one very minor issue I could find, when you hover over the chat input on Windows a tooltip appears saying "you are not friends anymore" even if user had just added them.
> Recording_2023-04-21_123105.mp4

I'll look into it but this seems impossible. I removed the tooltip from `textarea::Input` before submitting the PR.

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
I think I was missing the last commit, good now. Thank you @sdwoodbury

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
