### PR TITLE
update(createAccount): Login loading indicator

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Login loading indicator

https://github.com/Satellite-im/Uplink/assets/63157656/5d1ebb8e-5bbe-4a22-839d-001edb4ff2f2

### Which issue(s) this PR fixes 🔨

- Resolve #

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
when i click on the loader the app crashes

https://github.com/Satellite-im/Uplink/assets/29093946/afacd89f-961d-48d2-b6dd-40449829dc34


no crash on dev

flow is
- cargo run
- add pin
- click on the loader icon
- crash

i don't a have a crash log on uplink just a apple log

[message (14).txt](https://github.com/Satellite-im/Uplink/files/14502116/message.14.txt)

macOS, m1

**Comment by phillsatellite** [comment]
Only was able to replicate 1 out of 10 tries but also got mine to crash as well same flow as Sara

**Review by stavares843 — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
the crash is fixed but on the create account gets stuck on the loader

tried 3x

works on dev

image

macOS, m1

**Review by stavares843 — APPROVED** [review]
worked now 🎉

**Pull request merged**
