### PR TITLE
fix(Storage): Fix bug on storage with file preview

### LINKED ISSUE #713: Files - Crash when trying to create folder
**Issue:**
There is a crash on the files page, this is the flow on how to replicate 

Go to files page 
Preview a file 
Close preview 
Create Folder 
Before typing a name for the folder his the escape key

**OS**
MacOS

**Screen recording:**
https://user-images.githubusercontent.com/93608357/234071431-8b8502f9-be6e-4778-baf4-7c37ddb9b59a.mov

**Trace**
```
2023-04-24 13:31:34 | DEBUG | Loaded extension: "/Users/phillwisniewski/.uplink/extensions/libemoji_selector.dylib"
2023-04-24 13:31:34 | DEBUG | Loaded 1 extensions.
2023-04-24 13:31:34 | DEBUG | WARP CMD: MultiPass { InitializeFriends } 
2023-04-24 13:31:34 | INFO | list_incoming_request;
2023-04-24 13:31:34 | TRACE | rendering app
2023-04-24 13:31:34 | TRACE | rendering get_update_icon
2023-04-24 13:31:34 | TRACE | rendering app
2023-04-24 13:31:34 | TRACE | rendering get_update_icon
2023-04-24 13:31:34 | TRACE | -- list_incoming_request;
2023-04-24 13:31:34 | TRACE | init friends with 0 total
2023-04-24 13:31:34 | INFO | list_outgoing_request;
2023-04-24 13:31:34 | TRACE | rendering app
2023-04-24 13:31:34 | TRACE | rendering get_update_icon
2023-04-24 13:31:34 | INFO | Task started for 61e1a659-9fe3-9ddc-ec1d-13f33e9e4694
2023-04-24 13:31:34 | INFO | Event Task started for 61e1a659-9fe3-9ddc-ec1d-13f33e9e4694
2023-04-24 13:31:34 | INFO | RequestResponse Task started for 61e1a659-9fe3-9ddc-ec1d-13f33e9e4694
2023-04-24 13:31:34 | TRACE | -- list_outgoing_request;
2023-04-24 13:31:34 | INFO | block_list;
2023-04-24 13:31:34 | INFO | Listening on /ip4/24.199.86.91/tcp/46315/p2p/12D3KooWQcyxuNXxpiM7xyoXRZC7Vhfbh2yCtRg272CerbpFkhE6/p2p-circuit/p2p/12D3KooWCMFPGsgRBtGy4hw8axfrfwPVCL6YT5X3jhes8XdCMqyy
2023-04-24 13:31:34 | INFO | Task started for 0cd2d50c-e4e1-96e1-03d8-1abe97c8553c
2023-04-24 13:31:34 | INFO | Event Task started for 0cd2d50c-e4e1-96e1-03d8-1abe97c8553c
2023-04-24 13:31:34 | INFO | RequestResponse Task started for 0cd2d50c-e4e1-96e1-03d8-1abe97c8553c
2023-04-24 13:31:35 | TRACE | -- block_list;
2023-04-24 13:31:35 | INFO | Task started for dae33056-4046-35ab-d441-1f6da112f685
2023-04-24 13:31:35 | INFO | Event Task started for dae33056-4046-35ab-d441-1f6da112f685
2023-04-24 13:31:35 | INFO | RequestResponse Task started for dae33056-4046-35ab-d441-1f6da112f685
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:35 | INFO | Task started for 6d2a859c-70ca-9dcf-5f73-692e216a8c3c
2023-04-24 13:31:35 | INFO | Event Task started for 6d2a859c-70ca-9dcf-5f73-692e216a8c3c
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | INFO | identity_platform; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:35 | INFO | RequestResponse Task started for 6d2a859c-70ca-9dcf-5f73-692e216a8c3c
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | TRACE | -- identity_platform;
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | INFO | identity_platform; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:35 | INFO | Task started for 00a344c0-57da-4419-b2f9-a0deec70f606
2023-04-24 13:31:35 | INFO | Event Task started for 00a344c0-57da-4419-b2f9-a0deec70f606
2023-04-24 13:31:35 | INFO | RequestResponse Task started for 00a344c0-57da-4419-b2f9-a0deec70f606
2023-04-24 13:31:35 | INFO | MessagingStore task created
2023-04-24 13:31:35 | INFO | Loading queue
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | TRACE | -- identity_platform;
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | INFO | identity_platform; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | TRACE | -- identity_platform;
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | INFO | identity_platform; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | TRACE | -- identity_platform;
2023-04-24 13:31:35 | INFO | insert; peer_type=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:35 | TRACE | -- insert;
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | INFO | identity_platform; did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:35 | TRACE | -- identity_status;
2023-04-24 13:31:35 | TRACE | -- identity_platform;
2023-04-24 13:31:35 | TRACE | init friends
2023-04-24 13:31:35 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-24 13:31:35 | DEBUG | Updating directories opened to browse
2023-04-24 13:31:35 | INFO | Get items from current directory worked!
2023-04-24 13:31:35 | DEBUG | WARP CMD: RayGun { InitializeConversations } 
2023-04-24 13:31:35 | TRACE | init items
2023-04-24 13:31:35 | TRACE | rendering app
2023-04-24 13:31:35 | TRACE | init convs with 5 total
2023-04-24 13:31:35 | TRACE | rendering get_update_icon
2023-04-24 13:31:35 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | INFO | identity_platform; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | INFO | identity_status; did=did:key:z6MkjfdREzZpYAUsLeW3AaDgRjwVqCS1pqokTP8iK7WqHY2V
2023-04-24 13:31:36 | TRACE | -- identity_status;
2023-04-24 13:31:36 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6MkjZWwtnLztjmgRUDsNReoegXrFPepfQybLd4ZCfUHTM5f
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6MkrjdpzjFRXhyTQRGrdLhvFo5od5gYemTzstrhzE7f6e2K
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6Mkgz9G7zM9LXVwmKGQdvtMkEreXaKkqGgvU8CmapSKP83R
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | INFO | identity_platform; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:37 | INFO | identity_status; did=did:key:z6Mkf39Wu1S7if4iCFazYVr6r7J1XdPDxCtY9ezNe1Szn1P7
2023-04-24 13:31:37 | TRACE | -- identity_status;
2023-04-24 13:31:37 | TRACE | -- identity_platform;
2023-04-24 13:31:37 | TRACE | init chats
2023-04-24 13:31:37 | TRACE | rendering app
2023-04-24 13:31:37 | TRACE | rendering get_update_icon
2023-04-24 13:31:37 | TRACE | starting warp_runner use_future
2023-04-24 13:31:37 | TRACE | rendering compose
2023-04-24 13:31:37 | TRACE | get_messages
2023-04-24 13:31:37 | TRACE | render message groups
2023-04-24 13:31:38 | TRACE | get_chatbar
2023-04-24 13:31:38 | TRACE | render input
2023-04-24 13:31:38 | TRACE | rendering topbar
2023-04-24 13:31:38 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:38 | TRACE | get_messages
2023-04-24 13:31:38 | TRACE | render message groups
2023-04-24 13:31:38 | DEBUG | state::mutate: ChatWith
2023-04-24 13:31:38 | TRACE | rendering app
2023-04-24 13:31:38 | TRACE | rendering get_update_icon
2023-04-24 13:31:38 | TRACE | rendering compose
2023-04-24 13:31:38 | TRACE | rendering topbar
2023-04-24 13:31:38 | TRACE | get_messages
2023-04-24 13:31:38 | TRACE | render message groups
2023-04-24 13:31:38 | TRACE | get_chatbar
2023-04-24 13:31:38 | TRACE | render input
2023-04-24 13:31:38 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:38 | TRACE | get_messages
2023-04-24 13:31:38 | TRACE | render message groups
2023-04-24 13:31:39 | TRACE | rendering topbar
2023-04-24 13:31:39 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:40 | DEBUG | WARP CMD: Constellation { GetItemsFromCurrentDirectory } 
2023-04-24 13:31:40 | INFO | Get items from current directory worked!
2023-04-24 13:31:40 | TRACE | rendering topbar
2023-04-24 13:31:40 | TRACE | rendering topbar
2023-04-24 13:31:40 | TRACE | rendering app
2023-04-24 13:31:40 | TRACE | rendering get_update_icon
2023-04-24 13:31:40 | TRACE | rendering topbar
2023-04-24 13:31:40 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:40 | INFO | request; out_did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz option=Identity
2023-04-24 13:31:40 | TRACE | Payload size: 61 bytes
2023-04-24 13:31:40 | INFO | Sending event to did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | Event sent to did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | TRACE | Took 5ms to send event
2023-04-24 13:31:40 | TRACE | -- request;
2023-04-24 13:31:40 | INFO | push; out_did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | is_friend; pubkey=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | process_message; in_did=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | Received event from did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | DEBUG | Event: Receive { option: ResponseOption::Identity { identity: did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz } }
2023-04-24 13:31:40 | TRACE | -- process_message;
2023-04-24 13:31:40 | TRACE | -- is_friend;
2023-04-24 13:31:40 | INFO | is_blocked; public_key=did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | block_list;
2023-04-24 13:31:40 | TRACE | -- block_list;
2023-04-24 13:31:40 | TRACE | -- is_blocked;
2023-04-24 13:31:40 | TRACE | Including cid in push: true
2023-04-24 13:31:40 | TRACE | Payload size: 624 bytes
2023-04-24 13:31:40 | INFO | Sending event to did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | INFO | Event sent to did:key:z6MkkQVbWyuzdhMySZZc5qHdDQGjEu3qAoeD71MaLjQgfzAz
2023-04-24 13:31:40 | TRACE | Took 2ms to send event
2023-04-24 13:31:40 | TRACE | -- push;
2023-04-24 13:31:40 | TRACE | rendering app
2023-04-24 13:31:40 | TRACE | rendering get_update_icon
2023-04-24 13:31:40 | TRACE | rendering topbar
2023-04-24 13:31:40 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:41.705 uplink[51611:3024397] +[CATransaction synchronize] called within transaction
2023-04-24 13:31:46 | TRACE | rendering app
2023-04-24 13:31:46 | DEBUG | WARP CMD: Constellation { UploadFiles { files_path: ["/Users/phillwisniewski/Library/Mobile Documents/com~apple~CloudDocs/QA Tools/Sample Profile Pics/pic6.jpg"] }  } 
2023-04-24 13:31:46 | INFO | Starting upload for pic6.jpg
2023-04-24 13:31:46 | INFO | 0% completed -> written 0 bytes
2023-04-24 13:31:46 | INFO | 11% completed -> written 4.10 kB
2023-04-24 13:31:46 | INFO | 22% completed -> written 8.19 kB
2023-04-24 13:31:46 | INFO | 33% completed -> written 12.29 kB
2023-04-24 13:31:46 | INFO | 44% completed -> written 16.38 kB
2023-04-24 13:31:46 | INFO | 55% completed -> written 20.48 kB
2023-04-24 13:31:46 | INFO | 67% completed -> written 24.58 kB
2023-04-24 13:31:46 | INFO | 78% completed -> written 28.67 kB
2023-04-24 13:31:46 | INFO | 89% completed -> written 32.77 kB
2023-04-24 13:31:46 | INFO | 100% completed -> written 36.66 kB
2023-04-24 13:31:46 | TRACE | rendering get_update_icon
2023-04-24 13:31:46 | TRACE | rendering topbar
2023-04-24 13:31:46 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:46 | TRACE | rendering app
2023-04-24 13:31:46 | TRACE | rendering get_update_icon
2023-04-24 13:31:46 | TRACE | rendering topbar
2023-04-24 13:31:46 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:46 | INFO | pic6.jpg has been uploaded with 36.66 kB
2023-04-24 13:31:46 | INFO | Image Thumbnail uploaded
2023-04-24 13:31:46 | INFO | "pic6.jpg" file uploaded!
2023-04-24 13:31:46 | INFO | Get items from current directory worked!
2023-04-24 13:31:47 | TRACE | rendering topbar
2023-04-24 13:31:47 | TRACE | rendering app
2023-04-24 13:31:47 | TRACE | rendering get_update_icon
2023-04-24 13:31:47 | TRACE | rendering topbar
2023-04-24 13:31:47 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:48 | DEBUG | state::mutate: AddFilePreview
2023-04-24 13:31:48 | TRACE | rendering app
2023-04-24 13:31:48 | TRACE | rendering get_update_icon
2023-04-24 13:31:48 | TRACE | rendering topbar
2023-04-24 13:31:48 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:48 | TRACE | rendering app
2023-04-24 13:31:48 | TRACE | rendering get_update_icon
2023-04-24 13:31:48 | TRACE | rendering topbar
2023-04-24 13:31:48 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:48 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-24 13:31:48 | DEBUG | add_to_themes: ui/extra/themes
2023-04-24 13:31:48 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-24 13:31:48 | DEBUG | add_to_themes: ui/extra/themes
2023-04-24 13:31:48 | DEBUG | add_to_themes: /Users/phillwisniewski/.uplink/themes
2023-04-24 13:31:48 | DEBUG | add_to_themes: ui/extra/themes
2023-04-24 13:31:50 | DEBUG | state::mutate: ForgetFilePreview
2023-04-24 13:31:50 | TRACE | rendering app
2023-04-24 13:31:50 | TRACE | rendering get_update_icon
2023-04-24 13:31:50 | TRACE | rendering topbar
2023-04-24 13:31:50 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:50 | TRACE | rendering app
2023-04-24 13:31:50 | TRACE | rendering get_update_icon
2023-04-24 13:31:50 | TRACE | rendering topbar
2023-04-24 13:31:50 | TRACE | rendering chats sidebar layout
2023-04-24 13:31:51 | TRACE | rendering topbar
zsh: segmentation fault  cargo run trace2
```

### LINKED ISSUE #719: Files - Certain files are crashing when trying to preview
**Issue:**
When you are uploading files, there are certain files that I am finding that are causing Uplink to crash. I can add the profile into this ticket if needed and I will add the files that are causing my Uplink to crash 

**OS:**
All

**File:**
pic6

**Screen recording:**

https://user-images.githubusercontent.com/93608357/234354266-cbada2c1-dfd0-4d5b-8d74-c71a518eff80.mov

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix problem in Storage that was panic app after file preview 
a. For some reason it occurred because of new window with menu, so it now is avoided when new window for file preview is called 

image

- 

### Which issue(s) this PR fixes 🔨

- Resolve #713 
- Resolve #719

### CODE REVIEW

**Comment by stavares843** [comment]
Captura de ecrã 2023-04-25, às 20 13 45

**Comment by lgmarchi** [comment]
> Captura de ecrã 2023-04-25, às 20 13 45

Did change to solve it

**Comment by stavares843** [comment]
thanks @lgmarchi  🎨

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
the file that was crashing no longer crash's in my local

also tested a bunch of other files and no crash 🔨

**Review by sdwoodbury — APPROVED** [review]

**Pull request merged**
