### PR TITLE
task(groups): Change calling to only include joined participants

### LINKED ISSUE #1473: task(groups): Only show users who are in the call
**Task:**
In group calling, when the call starts every member of the group will show up in the calling UI, we should only show people who have answered the call. 

Screenshot 2023-11-07 at 1 27 43 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Makes it so calls only show joined participants

### Which issue(s) this PR fixes 🔨

- Resolve #1473### Additional comments 🎤

### CODE REVIEW

**Comment by phillsatellite** [comment]
@Flemmli97 Works well! Just had one suggestion but I guess it depends on what others think as well maybe @XileHorizon can give his opinion. Should we show users own profile within the call ui? Like when I place call and no one else has joined yet instead of showing "Nobody is here" the user would see just their profile avatar. We could also just add at a later more appropriate time in a different ticket if that works! 

https://github.com/Satellite-im/Uplink/assets/93608357/5b757dd8-a4a5-42a5-9f4b-c90ae2564ba0

**Comment by Flemmli97** [comment]
irrc in the past we wanted to exclude the current user from it. maybe im wrong though?

**Comment by phillsatellite** [comment]
> irrc in the past we wanted to exclude the current user from it. maybe im wrong though?

we can keep it like that  👍

**Review by sdwoodbury — APPROVED** [review]

**Comment by XileHorizon** [comment]
> @Flemmli97 Works well! Just had one suggestion but I guess it depends on what others think as well maybe @XileHorizon can give his opinion. Should we show users own profile within the call ui? Like when I place call and no one else has joined yet instead of showing "Nobody is here" the user would see just their profile avatar. We could also just add at a later more appropriate time in a different ticket if that works!
> 
>  Screen.Recording.2023-11-10.at.2.14.12.PM.mov

In my designs, I have the user icon in the bottom left corner. 
image

**Comment by phillsatellite** [comment]
@Flemmli97 if you want me to make a ticket for making call ui resemble figma designs and approve this Im cool with that

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
