### PR TITLE
chore(dependencies): update dioxus to 73a2beb3275007a6550adc5c420f36e31b7ddef7

### LINKED ISSUE #679: Windows - Trace2 not working
**Issue:** Like title says, when you run the command trace2 it will not work on Windows OS 

**STR:**
Run Uplink on Windows using trace2

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- allows configuring the Dioxus data directory
- fixes the windows installer - installs uplink to the ProgramFiles directory, and fixes uninstall
- note that on Linux, you have to install `libwebkit2gtk-4.1-dev`
- fixes logging on windows, for dev mode

### Which issue(s) this PR fixes 🔨

- Resolve #679

### Additional comments 🎤

image

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Stu, so during my time testing this I found a couple things I wanted to mention 

On a good note, I got it to build on Windows! (and as you already know I was having issues getting my Linux to build)

On these I replicated with and without clearing .uplink dir / cargo clean (These first bugs are only able to be replicated if you build the actual app onto Windows rather than doing cargo run)
1. When you build the actual app on Windows and go through the Desktop shortcut and either preview an uploaded file in the file panel, or try to open the emoji menu the app will crash

https://user-images.githubusercontent.com/93608357/233221425-cb4616a3-75b9-4a2b-b25b-f2bc052a559b.mp4

(This is able to be replicate by just doing cargo run)
2. In chat if you open Reactions or Edit message modal will close if you do not click anything. I also noticed Reactions will close asap the first time opened. 

https://user-images.githubusercontent.com/93608357/233221421-bcd9dc99-41a2-4fed-8864-873942e8f7a9.mp4

**Comment by sdwoodbury** [comment]
turns out that with the updated Dioxus, there's a BorrowMut error with extensions. This happened when I tried to use the emoji extension.
image
Not sure how to work around this. We might just be out of luck.

**Comment by sdwoodbury** [comment]
found a problem on Linux
image

**Comment by dariusc93** [comment]
> turns out that with the updated Dioxus, there's a BorrowMut error with extensions. This happened when I tried to use the emoji extension. image Not sure how to work around this. We might just be out of luck.

Yea I noticed that when testing the previous PR that it had a borrowmut with the extension. Its interesting that we havent seen it in the closures within uplink itself though (or at least not yet?). There are only 3 places where its used at there though, although imo, it might be best to go the coroutine route.

**Comment by sdwoodbury** [comment]
the BorrowMutError occurs with `use_shared_state`, not in `state.write()`. really weird. 
image

**Comment by sdwoodbury** [comment]
i believe that PR https://github.com/Satellite-im/Uplink/pull/701 will resolve the problem with EditMsg and reactions

**Comment by phillsatellite** [comment]
Bugs addressed earlier are gone 🌟

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
