### PR TITLE
update(CropImage): Add mask on crop tool

### PR DESCRIPTION
**Pull request by lgmarchi**
### 2. Add buttons to range element

https://github.com/Satellite-im/Uplink/assets/63157656/6898ec60-5c53-466c-80ad-d465ebd3e83c

### Which issue(s) this PR fixes 🔨

- Resolve #

### CODE REVIEW

**Comment by lgmarchi** [comment]
Wait until #1253 is merged

**Comment by phillsatellite** [comment]
I think in light mode the - and + button could be a little lighter, right now they seem kinda hard to see. Maybe thats more of an edge case and can be handled in another ticket? Other than that the function of this pr works well! 

Screenshot 2023-10-11 at 7 32 14 AM

**Review by phillsatellite — APPROVED** [review]

**Comment by lgmarchi** [comment]
> I think in light mode the - and + button could be a little lighter, right now they seem kinda hard to see. Maybe thats more of an edge case and can be handled in another ticket? Other than that the function of this pr works well!
> 
> Screenshot 2023-10-11 at 7 32 14 AM

Sometimes is difficult to find a color that works well in both themes, I will try to let a color good just for white theme.

**Comment by lgmarchi** [comment]
> I think in light mode the - and + button could be a little lighter, right now they seem kinda hard to see. Maybe thats more of an edge case and can be handled in another ticket? Other than that the function of this pr works well!
> 
> Screenshot 2023-10-11 at 7 32 14 AM

Done my friend. 

Dark theme: 
image



Light theme: 
image

**Review by phillsatellite — APPROVED** [review]

**Review by sdwoodbury — APPROVED** [review]

**Pull request merged**
