### PR TITLE
chore(license): Relicense to MIT

### PR DESCRIPTION
**Pull request by zeenix**
### What this PR does 📖

The current CCC license is not appropriate for software and it would be best to have a proper license before any external parties contribute. Otherwise, we would have to ask their permission before re-licensing.
    
After discussion with the team, we have decided to relicense the project to MIT.

### Special notes for reviewers 🗒️

I just copied the `LICENSE` file from the `Warp` repo. I think we want it to be kept in sync with the `Warp` repo.

### CODE REVIEW

**Review by tooshel — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
the new file isn't .MD is that on purpose?

**Comment by zeenix** [comment]
> the new file isn't .MD is that on purpose?

I wanted to get this done ASAP and wasn't having luck finding it in .md format so I just copied from `Warp` repo.

**Comment by zeenix** [comment]
> > the new file isn't .MD is that on purpose?
> 
> I wanted to get this done ASAP and wasn't having luck finding it in .md format so I just copied from `Warp` repo.

Besides if you look into the file, you'll find that it's super simple and has a few paragraphs. So not sure finding it in markdown or converting it, is worth the trouble.

**Comment by stavares843** [comment]
i did look at the file but was just a question considering the previous one as in fact a .md extension

**Pull request merged**
