### PR TITLE
chore(ci): Update actions

### PR DESCRIPTION
**Pull request by zeenix**
### What this PR does 📖

* Update `actions/checkout` to version 4.
* Switch from `actions-rs/toolchain` to `dtolnay/rust-toolchain`. The former has been archived and is no longer maintained.

### CODE REVIEW

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
seems fine i want @luisecm as well on this

**Comment by luisecm** [comment]
Looks good to me, upgrading checkout action is fine. Let's wait until CI finishes just to prove that build and test works normally under this new dtolnay/rust-toolchain@master action

**Comment by stavares843** [comment]
sounds good, thanks for taking a look @luisecm 🎉

**Review by luisecm — APPROVED** [review]
Looks good! build actions ran correctly

**Pull request merged**
