### PR TITLE
feat(dev): Dev tools update

### LINKED ISSUE #1270: task(ui): Context menu for Inspect Elements could be displayed only when developer mode is on
Currently all users can right click on the app and see the Context Menu for Inspect Element. Brought this to the QA team and we agreed that it would be good that only users with Developer Mode can see this context menu, instead of all users.

Tested on: MacOS latest dev

Prerequisites:
Account created

Steps to reproduce:

1. Login to the app
2. Go to settings and ensure that the current user has Developer Mode disabled
3. Right click on any part of the app
4. Reload/Inspect Elements context menu is shown for the user

Video:
https://github.com/Satellite-im/Uplink/assets/35935591/25943ade-67c3-4536-bccc-93efbedbd552

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Continuation of #1247:
  - Makes it so default element inspection is disabled and thus allows only the inspect window to be opened via our own `Open Console` button

### CODE REVIEW

**Comment by tooshel** [comment]
It works exactly how I had hoped! With the toggle on or off, right clicking shows nothing unless it's a place we want right clicking, and you only see the "Open Console" option if you toggle on the dev tools option in the app. Nicely done! 

image

**Review by tooshel — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Comment by dariusc93** [comment]
I wonder if we should hold off to merging this until #1243 is resolved. Thoughts?

**Comment by Flemmli97** [comment]
removed labels now that the issue is resolved

**Comment by tooshel** [comment]
Darius wanted to wait till we got the windows bug fixed but that issue is closed now. We can (and should) merge this. Right now, in the released version of the app, we have the Edge dev tools popping up if we don't have a right click handler and it's not what we want.

**Review by tooshel — APPROVED** [review]
I tested it when he first made the change and it worked as expected. Phill is trying it again to verify!

**Comment by phillsatellite** [comment]
Seems good still! Waiting for ci to finish till approved 👍

**Review by stavares843 — COMMENTED** [review]
doing right click still shows the option here

image

**Comment by phillsatellite** [comment]
> doing right click still shows the option here
> 
> image

If anyone with 13x MacOS can try to replicate that, I dont think this happens on 14x Sonoma I cant replicate no matter where I click

**Comment by Flemmli97** [comment]
are you running in debug or release mode? its only in release where it doesn't show

**Comment by stavares843** [comment]
ohh was debug, gonna try with release

thanks! 🔨

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
doesn't appear in release 🎉

**Pull request merged**
