### PR TITLE
update(Folder): Validate on return in folder name when name is empty

### LINKED ISSUE #982: bug(files): if you try to add a folder without name no warning appears
STR:
- go to files
- add a folder
- no name
- enter
- no error
- add a letter and erase it 
- now warning appears

https://github.com/Satellite-im/Uplink/assets/29093946/16ac908a-f846-4ebf-855b-3c4a4ccb3d5a

macOS

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Validate on return in folder name when name is empty

https://github.com/Satellite-im/Uplink/assets/63157656/2f6e0e58-d9d0-4394-b16a-b98ce2630191

### Which issue(s) this PR fixes 🔨

- Resolve #982

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2023-07-14, às 18 06 26


error trying to compile

macOS, m1

**Comment by phillsatellite** [comment]
Same error on Windows and MacOS with m2

**Comment by lgmarchi** [comment]
> Same error on Windows and MacOS with m2

It happened when solving conflicts, just some minutes to solve it

**Review by stavares843 — APPROVED** [review]

**Review by sdwoodbury — APPROVED** [review]
LGTM

**Pull request merged**
