### PR TITLE
fix(chatbar): Fix typing indicator moving chatbar

### LINKED ISSUE #1259: bug(ui): Chatbox height will adjust when someone is typing
**Issue:**
When someone in chat is typing to you, the entire chatbox's height will adjust up a little. We should have it so chatbox position doesnt move when someone is typing to you 

**OS:**
Mac
Linux
Windows

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/2f1a55f4-ff09-4e30-a390-48ffe7fdd702

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes typing indicator moving chatbar

### Which issue(s) this PR fixes 🔨

- Resolve #1259

### CODE REVIEW

**Comment by stavares843** [comment]
i noticed his PR adds a submodule, is that in purpose? @Flemmli97 🔨

**Comment by stavares843** [comment]
the bug is fixed 🎉

**Comment by Flemmli97** [comment]
idk why that got it but it has nothing to do with uplink... i removed it

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
thanks 🎉

**Pull request merged**
