### PR TITLE
chore(githubAction): fix typos

### PR DESCRIPTION
**Pull request by stavares843**
**What this PR does** 📖

Adds a Github Action that automatically adds a PR when it sees any typos.

### CODE REVIEW

**Comment by InfamousVague** [comment]
There is a typo in dioxus that needs to be fixed; we should hold off on this until we can make sure it passes.

**Comment by stavares843** [comment]
Captura de ecrã 2022-12-30, às 14 41 48

on my forked repo, the only typo that appeared was this one 🔨

**Comment by dariusc93** [comment]
> Captura de ecrã 2022-12-30, às 14 41 48
> 
> on my forked repo, the only typo that appeared was this one hammer

I believe hes referring to the one found in https://github.com/Satellite-im/Uplink-UI/pull/27#pullrequestreview-1230610821

**Comment by stavares843** [comment]
ohh k 😂

**Pull request merged**
