### PR TITLE
feat(groups): Allow any char in group names

### LINKED ISSUE #1030: improvement(groups): allow symbols when creating group
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Allows any character in group names. 

### Which issue(s) this PR fixes 🔨

- Resolve #1030

### Additional comments 🎤
I am not sure if allowing any characters will cause any problems down the line but I see how it would.
If it does we probably want just a list of allowed special characters. (e.g. like `/._-` etc.)

### CODE REVIEW

**Comment by dariusc93** [comment]
It might be best to allow only specific characters instead of any just to be safe since I can imagine it being problematic down the road

**Comment by stavares843** [comment]
added label due to darius comment

**Comment by Flemmli97** [comment]
changed to specific list. current allowed are ` .,!?_&+~(){}[]+-/*`. Which should cover the most commonly used ones

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Comment by stavares843** [comment]
Captura de ecrã 2023-07-25, às 18 29 43

we should update the copy also, i can add a PR for that

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
