### PR TITLE
update(PopoutPlayer): Update UI when close popout player

### LINKED ISSUE #98: Close Popout UI not updating through app
**Issue:** Like title says ClosePopout UI is not updating through app. Found this bug on Lucas's latest pr he has fix for it already 👍

### LINKED ISSUE #99: Cant close popout after opening first time
**Issue:** Other issue I found on Lucas's latest PR. If we Update the UI to be Media Detached when we open the Pop out player, it will not be possible for the User to re open the pop out player using the pop out button. 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/211399716-95a10bee-1907-41d0-a1eb-943c8a1c243d.mov

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Update UI when close pop out player 

https://user-images.githubusercontent.com/63157656/211402115-12ded82a-648f-42a1-9718-eb3b077404a3.mov

### 2. Close Popout player by popout button 

https://user-images.githubusercontent.com/63157656/211402225-9db68236-12d5-494c-9a73-3080dcb4d4b2.mov

### 3. Temp bypass solution for auth page 
image

- 

### Which issue(s) this PR fixes 🔨

- Resolve #98 
- Resolve #99

### CODE REVIEW

**Review by phillsatellite — APPROVED** [review]

**Comment by sdwoodbury** [comment]
https://user-images.githubusercontent.com/8636602/211590175-e6e03a60-d13e-44c8-9e43-a82a21abbdca.mp4

adding the prop to the MediaPlayer doesn't work if you switch chats. I can make another PR to show an alternative solution

**Comment by lgmarchi** [comment]
> popout-bug-2023-01-10_10.18.00.mp4 
> adding the prop to the MediaPlayer doesn't work if you switch chats. I can make another PR to show an alternative solution

Hum... It is lost reference when we switch chats, I think I can know a solution for it, let me test

**Comment by lgmarchi** [comment]
> popout-bug-2023-01-10_10.18.00.mp4 
> adding the prop to the MediaPlayer doesn't work if you switch chats. I can make another PR to show an alternative solution

Stu, it is been difficult to find a complete solution, if I fix one part, one doesn't work more. I will open a new ticket for this

**Review by phillsatellite — APPROVED** [review]

**Comment by sdwoodbury** [comment]
this PR can be abandoned in favor of https://github.com/Satellite-im/Uplink/pull/114

**Pull request closed without merging**
