### PR TITLE
fix(keybinds): add state calls to mute and deafen keybindings

### LINKED ISSUE #1842: bug(keyBindings): Mute/unmute deafen/undeafen not working
**Issue:**
Like title says the keybindings for mute/unmute and deafen/undeafen are not working while in a call. In the log it shows that the keybinding is being pressed but UI never updates 

**OS:**
Mac 
Windows 
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/b4dca1d0-8525-4627-8d4a-0b6937468234

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- Add the state calls to shortcut handler file

### Which issue(s) this PR fixes 🔨

- Resolve #1842

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey @Jekrimo! Noticed a few things while testing 

It seems like when the user mutes with the keybindings it doesnt actually mute them, just updates the UI. So it will appear that you are muted but you are not. 

Another thing I saw was if your friend on the other end of the call is muted, the icon to show that they are doesnt appear (image below is from dev and shows the icon that doesnt appear on this branch) 
image

**Comment by Jekrimo** [comment]
Weird! I'm on it, thank you @phillsatellite !!

**Comment by dariusc93** [comment]
You should be able to use https://github.com/Satellite-im/Uplink/blob/731d8447bb11e5fb875d3c8f3eadd7314132722c/common/src/warp_runner/manager/commands/blink_commands.rs#L35-L42 to mute/unmute (although im not sure if it ever was tested though)

**Comment by Jekrimo** [comment]
> You should be able to use
> 
> https://github.com/Satellite-im/Uplink/blob/731d8447bb11e5fb875d3c8f3eadd7314132722c/common/src/warp_runner/manager/commands/blink_commands.rs#L35-L42
> 
> to mute/unmute (although im not sure if it ever was tested though)

Thanks @dariusc93 ! I didn't track back that far but super good to know.
I think I found how to call them and got them in the keybinds for audio...
They are currently working for mute and deafen, but I'm trying to get the async to function proper so that we can catch the errors, also need to figure out a toggle work around that will check if currently muted/deafen and visversa (maybe a simple bool stored in state). I think if I also pass in the cx along with state it may work out but wrote myself into a million errors yesterday so going to try again today. Currently all the call handling is happening in the component here, https://github.com/Satellite-im/Uplink/blob/731d8447bb11e5fb875d3c8f3eadd7314132722c/ui/src/components/media/calling.rs#L140-L309
 
image

**Comment by luisecm** [comment]
We noticed that this weird bug is happening on this branch the app is gone and just showing the minimize, maximize, close buttons after entering pin:

image

Also, we see some warnings are shown after running cargo build release on this branch:

image

**Comment by phillsatellite** [comment]
I also replicated what @luisecm mentioned above on MacOS, Linux, and Windows

**Comment by Jekrimo** [comment]
Thanks guys, I was hoping I would get some extra error logs but alas it seems not. I know what is doing it, just can't figure *why*

**Comment by dariusc93** [comment]
Converting this to draft since it is still being worked on

**Review by lgmarchi — APPROVED** [review]
Approved.

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
@luisecm  took a look and he noticed the following

you have to press twice the keybind to make it work

and he also saw this on the logs

```
024-03-13 13:50:40 | DEBUG | shortcut called ToggleMute
2024-03-13 13:50:40 | DEBUG | WARP CMD: Blink { MuteSelf } 
2024-03-13 13:50:40 | DEBUG | state::mutate: ToggleMute
2024-03-13 13:50:40 | ERROR | /Users/luisecm/.cargo/git/checkouts/warp-2f0b6768b713aeb1/d15be57/extensions/warp-blink-wrtc/src/blink_impl/gossipsub_sender.rs:293 | failed to publish aes message: InsufficientPeers
panicked at /Users/luisecm/.cargo/git/checkouts/dioxus-16f84e4ea3809fe4/1dba57f/packages/core/src/scopes.rs:561:14:

                Unable to retrieve the hook that was initialized at this index.
                Consult the `rules of hooks` to understand how to use hooks properly.

                You likely used the hook in a conditional. Hooks rely on consistent ordering between renders.
                Functions prefixed with "use" should never be called conditionally.
                
2024-03-13 13:50:40 | DEBUG | shortcut called ToggleMute
2024-03-13 13:50:40 | DEBUG | WARP CMD: Blink { MuteSelf } 
2024-03-13 13:50:40 | DEBUG | state::mutate: ToggleMute
2024-03-13 13:50:40 | ERROR | /Users/luisecm/.cargo/git/checkouts/warp-2f0b6768b713aeb1/d15be57/extensions/warp-blink-wrtc/src/blink_impl/gossipsub_sender.rs:293 | failed to publish aes message: InsufficientPeers

The crash has been saved to ../cache/luisqa12/crash-logs/13-03-2024_13-50-41.log
2024-03-13 13:50:42 | DEBUG | shortcut called ToggleDeafen
2024-03-13 13:50:42 | DEBUG | WARP CMD: Blink { SilenceCall } 
2024-03-13 13:50:42 | DEBUG | state::mutate: ToggleSilence
``` 

video

https://github.com/Satellite-im/Uplink/assets/29093946/6e042526-39a5-46fa-8902-58a03f51e5d3

macOS, sonoma

**Comment by Jekrimo** [comment]
Hey Guys! Sorry for the delay on this and thanks for the testing! I've been testing between the mac and the pc and it seems to be hitting first time without any of the errors. I also tested running instances side by side on the mac and was also unable to reproduce, (Even went to extension tab just encase and nope, still couldn't get it). I'm wondering if maybe a dev update got through on a merge that could have fixed the problem? If you would be so kind as to test again, and we can cross fingers and hope some magical elf fixed it? @stavares843 @luisecm

**Comment by luisecm** [comment]
> Hey Guys! Sorry for the delay on this and thanks for the testing! I've been testing between the mac and the pc and it seems to be hitting first time without any of the errors. I also tested running instances side by side on the mac and was also unable to reproduce, (Even went to extension tab just encase and nope, still couldn't get it). I'm wondering if maybe a dev update got through on a merge that could have fixed the problem? If you would be so kind as to test again, and we can cross fingers and hope some magical elf fixed it? @stavares843 @luisecm

@Jekrimo @stavares843 lol, I just retested again and it looks good, I do not see the issue anymore with toggle deafen/undeafen, mute/unmute anymore. I am thinking that the change from @lgmarchi about the order of keybinds recently merged could have helped on this? Anyway, it works good now!

**Review by stavares843 — APPROVED** [review]

**Comment by stavares843** [comment]
thanks @luisecm and @phillsatellite 🎉

**Pull request merged**
