### PR TITLE
feat(misc): UI tweaks sep

### PR DESCRIPTION
**Pull request by InfamousVague**

### CODE REVIEW

**Comment by InfamousVague** [comment]
image
Tweaked main files layout page

**Comment by InfamousVague** [comment]
image

Tweaked UI for uploading file attachments in messag

**Comment by InfamousVague** [comment]
image

Tweaked popup modal for browsing local files

**Review by lgmarchi — APPROVED** [review]
Approved!

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
