### PR TITLE
update(FilePreview): Change file preview window to modal

### LINKED ISSUE #793: Modal File Preview (MFP) (instead of new window)
Make file previews open up in the modal, instead of a popout window.

@sdwoodbury put a modal in that is currently being used for updates - instructions to step through. You might be able to re-use this modal for file previews that scales to be however big the uplink window is.

If you are able to remove this from the popout, can you also remove Actions/State from the topbar_controls, to fix the issue with state not being available not showing the close windows on the uplink login screen on windows and linux

Related to #765

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Change file preview window to modal

https://github.com/Satellite-im/Uplink/assets/63157656/1906f647-d00c-452f-9030-a15c0a13abc5

### Which issue(s) this PR fixes 🔨

- Resolve #793

### CODE REVIEW

**Comment by phillsatellite** [comment]
This is working so well on all the OS's I just have one suggestion, should we disable right clicking it while in preview? Right now right clicking and selecting one of those options does not work 

https://github.com/Satellite-im/Uplink/assets/93608357/e0d3177f-5022-45c8-befa-170d6b364c6d

**Comment by lgmarchi** [comment]
> This is working so well on all the OS's I just have one suggestion, should we disable right clicking it while in preview? Right now right clicking and selecting one of those options does not work
> 
>  Screen.Recording.2023-05-09.at.1.37.43.PM.mov

I think is possible to do that, give me some minutes

**Comment by lgmarchi** [comment]
> This is working so well on all the OS's I just have one suggestion, should we disable right clicking it while in preview? Right now right clicking and selecting one of those options does not work
> 
>  Screen.Recording.2023-05-09.at.1.37.43.PM.mov

Done!

**Review by WanderingHogan — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
app crash's when you click the preview

STR:
- go to files
- add any image
- click
- crash's


macOS, m1

https://gist.github.com/stavares843/15a9ef2d52fdc36b56fda931e3219a20

**Comment by WanderingHogan** [comment]
for what it's worth i can't replicate the crash on macos ventura or on windows yet

**Comment by lgmarchi** [comment]
> app crash's when you click the preview
> 
> STR:
> 
> * go to files
> * add any image
> * click
> * crash's
> 
> macOS, m1
> 
> https://gist.github.com/stavares843/15a9ef2d52fdc36b56fda931e3219a20

Could you be more specific in steps? I didn't have any crash here

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Uplink/assets/29093946/779be07f-cd12-43c0-9088-2e589b8dd55c

**Comment by stavares843** [comment]
sheldon also has the same crash in windows

**Comment by stavares843** [comment]
also linter is failing 🔨

**Comment by tooshel** [comment]
> sheldon also has the same crash in windows

My crash happened to be on dev . . . but when I did switch to this branch I couldn't get it to crash again when clicking on a preview.

**Comment by stavares843** [comment]
here is always reproducible either when going to files > uploading a image > clicking > crash

**Comment by stavares843** [comment]
linter is failing 🔨

**Comment by lgmarchi** [comment]
> here is always reproducible either when going to files > uploading a image > clicking > crash

I didn't have any crash on MacOS, m1 or Windows 11, but I commited new code, try in your side please

**Comment by stavares843** [comment]
gonna try thanks 🔨

**Comment by stavares843** [comment]
yes still crash's 🔨

**Review by dariusc93 — APPROVED** [review]

**Comment by sdwoodbury** [comment]
looks good though I noticed that when previewing a file, it isn't always clear where I have to click in order to close the modal. Maybe a more pronounced background or an `X` button would be helpful. 

image

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
