### PR TITLE
chore(ai): code review

### PR DESCRIPTION
**Pull request by stavares843**
### What this PR does 📖

- Trying out AI code review

### CODE REVIEW

**Review by sdwoodbury — COMMENTED** [review]
question: will this merge in PRs automatically?

**Comment by stavares843** [comment]
no merging, just a bot saying what he thinks about the code 😂

**Comment by stavares843** [comment]
example

image

**Review by sdwoodbury — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Comment by dariusc93** [comment]
Have this been tested out any on uplink to get any ideas on how it would give its "thoughts" on the code? Will it be in a single response or over multiple responses? 

(label is there so nobody will merge it yet)

**Comment by stavares843** [comment]
one way we can test this, is to add some sample rust code in here and see what the bot does

i tested this locally, hence the screenshot above but not in the CI

**Comment by stavares843** [comment]
just added a rust sample code full of bugs to see what the bot does 😂

**Comment by stavares843** [comment]
so bot was running he says

LGTM! :+1:


lol 😅 

@dariusc93 what are your thoughts in that code? the [sample.rs](https://github.com/Satellite-im/Uplink/pull/711/files#diff-03c1ef9b8ebd1173df206531337ba044996c48149d1764aa19418fb114b71d73) thing i've added in the PR

chatGTP says it has the following errors

```

This code contains several errors:

Line 8 tries to add a string and an integer together.
Line 12 tries to access an index that is out of bounds for the vector v.
Line 16 tries to assign the result of a string concatenation to a variable that is not mutable.
Line 18 tries to assign an integer value to a variable that has been explicitly declared as an i32.
Line 20 tries to access an element of a tuple that doesn't exist.
Line 24 tries to pop a character from an empty string.
Line 26 tries to access an index that is out of bounds for the array arr.
Line 30 uses an incorrect syntax to format a string.
Line 36 compares an Option<i32> to None using the wrong operator.
```

**Comment by dariusc93** [comment]
> ```
> 
> This code contains several errors:
> 
> Line 8 tries to add a string and an integer together.
> Line 12 tries to access an index that is out of bounds for the vector v.
> Line 16 tries to assign the result of a string concatenation to a variable that is not mutable.
> Line 18 tries to assign an integer value to a variable that has been explicitly declared as an i32.
> Line 20 tries to access an element of a tuple that doesn't exist.
> Line 24 tries to pop a character from an empty string.
> Line 26 tries to access an index that is out of bounds for the array arr.
> Line 30 uses an incorrect syntax to format a string.
> Line 36 compares an Option<i32> to None using the wrong operator.
> ```

Is that in regards to the sample file? If so, it is off because

1. Line 12 is a `else` statement so its not trying to access an index that is out of bounds
2. Line 16 is a vector
3. Line 18 is a blank line
4. Line 20 is a string, not a tuple
5. Line 24 is a new i32 variable
6. Line 26 is a tuple, not an array
7. Line 30 is a new string, which is correct
8. Line 36 is a string

**Comment by stavares843** [comment]
yes so, the bot from the PR says is all good

he replied LGTM

but then i asked chatGTP and he said that list of bugs about that file yes lol

**Comment by stavares843** [comment]
so based on your reply both bot and chatgpt are wrong right? lol

**Comment by dariusc93** [comment]
> so based on your reply both bot and chatgpt are wrong right? lol

The problem is mostly that the lines in the quote there dont add up with the lines in the sample.rs that is problematic. Lining it up, the problems are there, such as out of bounds, trying to add a string to an int, invalid element for the tuple, trying to print a `Option`, etc. (just stuff i can visibly see producing an error without running the code - pretty sure passing the sample into playground or in the IDE would show the errors and/or warnings).

**Comment by stavares843** [comment]
yes got it lol but that feedback wasn't from this bot, this bot only said ''LGTM'' so even worse than the bad feedback from chatGTP 😅

**Comment by stavares843** [comment]
will close the PR because bot doesn't work he just says LGTM

**Pull request closed without merging**
