### PR TITLE
fix(TouchPad): Fix context menu with touch pad when there is dialog

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]
nice

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2023-12-11, às 22 55 55


i was still able to reproduce, it opens both the menu and the preview

macOS 13.6

**Comment by lgmarchi** [comment]
> Captura de ecrã 2023-12-11, às 22 55 55
> 
> i was still able to reproduce, it opens both the menu and the preview
> 
> macOS 13.6

Did you use control and click with touchpad right?

**Comment by stavares843** [comment]
@lgmarchi yes that is correct

**Comment by lgmarchi** [comment]
@stavares843 I have tested again, no problem happened here.

**Comment by stavares843** [comment]
will send video

**Comment by lgmarchi** [comment]
Here, I am testing with touchpad. 

https://github.com/Satellite-im/Uplink/assets/63157656/61e4656a-086b-4bcd-85cf-1dec0f65ac32

**Comment by stavares843** [comment]
works great now lol all good 😂 


cant reproduce the issue atm

**Review by stavares843 — APPROVED** [review]

**Comment by lgmarchi** [comment]
> works great now lol all good 😂
> 
> cant reproduce the issue atm

Hehehe Ok, no problem!

**Pull request merged**
