### PR TITLE
fix(group): Fix clear button in group creation not resetting

### LINKED ISSUE #896: bug(groups): after clearing user input, list of users is not displayed again
1. Go to create group modal
2. Add a group name
image

3. On users input, type anything that will return nothing (like "z", in the screenshot below)
image

4. Click on the button to clear input (or manually remove the previous input) on users input text, then the list of users is not refreshed as before typing in the input bar. Assuming that if no filter text is there, then all users should be displayed again and then this would be an issue
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fix clear button on user filter in group creation not resetting the filter

### Which issue(s) this PR fixes 🔨

- Resolve #896

### CODE REVIEW

**Comment by phillsatellite** [comment]
@Flemmli97 Works very well on MacOS and Windows! 🔥 On Linux I was still able to replicate the bug. I would search in group, clear it, group members remained blank. Maybe someone with a real linux machine could try to replicate this so we know its not a VM problem? 

https://github.com/Satellite-im/Uplink/assets/93608357/0f610866-01ea-4838-95cb-3c1abd89609c

I also noticed this while testing, if you go into the Members list in Groups, and do this same flow (type in a name and then clear it) the members in the list will not re-appear. Is this something you think would be easy to handle within this PR or would we wanna handle it in a separate ticket? (I replicated this on dev branch as well so if its easier to handle in another ticket thats cool with me! 😄)

https://github.com/Satellite-im/Uplink/assets/93608357/0d286ede-83c6-4629-8876-1426eb7fa61a

**Comment by Flemmli97** [comment]
strange. i did it on a linux machine. not vm

**Comment by phillsatellite** [comment]
@Flemmli97 with the latest commit, this is now working on my Linux VM 🎉  Once you make that commit for the members list in a Group as well I will test and hopefully approve! 💥

**Comment by Flemmli97** [comment]
> @Flemmli97 with the latest commit, this is now working on my Linux VM tada Once you make that commit for the members list in a Group as well I will test and hopefully approve! boom

that should already be in it

**Comment by Flemmli97** [comment]
btw should we make the search filter case insensitive? as its currently case sensitive so finding someone is a bit harder

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
> btw should we make the search filter case insensitive? as its currently case sensitive so finding someone is a bit harder

https://github.com/Satellite-im/Uplink/issues/921 Created ticket here. PR is all good and approved on my side after ci is done running, thanks @Flemmli97 😄

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
