### PR TITLE
fix(chat): fix not escaping for inline codeblocks and url parsing issues

### LINKED ISSUE #1731: bug(chat): chars not encoding properly
STR:
- send this

```
This is `javascript:alert('XSS Attack')` inline code.
```

how it sends vs what is displayed in the chat bar

image

image

also happens with this 

```<img src=x onerror="alert(1)" onmouseover="alert(2)">
``` 

Captura de ecrã 2024-01-17, às 23 19 18

image

macOS, m1

### LINKED ISSUE #1744: bug(chat): external resource inclusion
STR:
- go to chat
- send this

```
![External Image](http://malicious-site.com/image.jpg)
```

display like this

Captura de ecrã 2024-01-19, às 14 40 37

not sure what behavior do we prefer here

discord displays like this

Captura de ecrã 2024-01-19, às 20 18 52

macOS, m1

### LINKED ISSUE #1745: bug(chat): url encoding not displaying properly
STR:
- go to chat
- send this

```
[GitHub](https://www.github.com) is a code hosting platform for version control and collaboration.
``` 

on the chat after sending is displaying a > after the url

Captura de ecrã 2024-01-19, às 14 35 31

macOS, m1

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fix escaping issue with inline codeblocks
- Fix url parsing
- URL and Image markdown are now ignored as we do links separate from markdown

### Which issue(s) this PR fixes 🔨

- Resolve #1731
- Resolve #1744
- Resolve #1745

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
the first thing in the ticket is fixed

Captura de ecrã 2024-01-30, às 19 09 06

but the second isn't

sending 



still shows this
Captura de ecrã 2024-01-30, às 19 09 00


macOS, m1

**Review by stavares843 — COMMENTED** [review]
https://github.com/Satellite-im/Uplink/issues/1745 - fixed
https://github.com/Satellite-im/Uplink/issues/1744 - fixed
https://github.com/Satellite-im/Uplink/issues/1731 - fixed

**Review by stavares843 — CHANGES_REQUESTED** [review]
sending www.google.pt

this branch

Captura de ecrã 2024-02-01, às 17 02 14


vs dev

Captura de ecrã 2024-02-01, às 17 02 58

**Comment by stavares843** [comment]
sending this

```
# Extended Markdown Test

## Table of Contents

- [Headers](#headers)
- [Emphasis](#emphasis)
- [Lists](#lists)
- [Links](#links)
- [Images](#images)
- [Blockquotes](#blockquotes)
- [Code](#code)
- [Horizontal Rule](#horizontal-rule)
- [Tables](#tables)
- [Task Lists](#task-lists)
- [Definition Lists](#definition-lists)
- [Code Blocks](#code-blocks)
- [Strikethrough](#strikethrough)
- [Fenced Code Blocks with Language Specification](#fenced-code-blocks-with-language-specification)
- [Footnotes](#footnotes)
- [Superscript and Subscript](#superscript-and-subscript)
- [Emoji](#emoji)
- [LaTeX Math](#latex-math)
``` 

this branch

Captura de ecrã 2024-02-01, às 18 14 13


vs dev

Captura de ecrã 2024-02-01, às 18 14 57

**Comment by stavares843** [comment]
Captura de ecrã 2024-02-01, às 18 18 01

when sending this


```
![Image](data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8sIFdvcmxkISIpPC9zY3JpcHQ+Cg==)
``` 

it appears clickable on the preview but then when sending it isnt


Captura de ecrã 2024-02-01, às 18 21 18



this is on dev

so im not saying it should be on dev in this case, but if is not gonna be clickable when sending should not be clickable in the preview

**Comment by stavares843** [comment]
this branch

Captura de ecrã 2024-02-01, às 18 18 20

vs dev

Captura de ecrã 2024-02-01, às 18 22 19

content

```
[Click me](javascript:window.location='http://malicious-site.com')
``` 

should not be displaying this 

Captura de ecrã 2024-02-01, às 18 24 19

**Comment by Flemmli97** [comment]
> sending this
> 
> ```
> # Extended Markdown Test
> 
> ## Table of Contents
> 
> - [Headers](#headers)
> - [Emphasis](#emphasis)
> - [Lists](#lists)
> - [Links](#links)
> - [Images](#images)
> - [Blockquotes](#blockquotes)
> - [Code](#code)
> - [Horizontal Rule](#horizontal-rule)
> - [Tables](#tables)
> - [Task Lists](#task-lists)
> - [Definition Lists](#definition-lists)
> - [Code Blocks](#code-blocks)
> - [Strikethrough](#strikethrough)
> - [Fenced Code Blocks with Language Specification](#fenced-code-blocks-with-language-specification)
> - [Footnotes](#footnotes)
> - [Superscript and Subscript](#superscript-and-subscript)
> - [Emoji](#emoji)
> - [LaTeX Math](#latex-math)
> ```
> 
> this branch
> 
> Captura de ecrã 2024-02-01, às 18 14 13
> vs dev
> 
> Captura de ecrã 2024-02-01, às 18 14 57

idk if we want it though? isnt that basically a hidden link?

**Comment by stavares843** [comment]
i get your point, fine with it 

i mean that is useful for things like github and what not but on uplink the link is not gonna work so we can ignore that

**Comment by luisecm** [comment]
> sending [www.google.pt](http://www.google.pt)
> 
> this branch
> 
> Captura de ecrã 2024-02-01, às 17 02 14
> vs dev
> 
> Captura de ecrã 2024-02-01, às 17 02 58

This one specifically is affecting the CI automation tests:

User A sends a message with www.apple.com
User B receives a message with www.apple.com text and not an attached link

Chat User - Chat Messages containing links contents on local side - Failed

**Comment by stavares843** [comment]
thanks for checking @luisecm 🔨

**Comment by stavares843** [comment]
Captura de ecrã 2024-02-01, às 18 18 01

when sending this


```
![Image](data:text/html;base64,PHNjcmlwdD5hbGVydCgiSGVsbG8sIFdvcmxkISIpPC9zY3JpcHQ+Cg==)
``` 

it appears clickable on the preview but then when sending it isnt


Captura de ecrã 2024-02-01, às 18 21 18



this is on dev

so im not saying it should be on dev in this case, but if is not gonna be clickable when sending should not be clickable in the preview

**Comment by Flemmli97** [comment]
> Captura de ecrã 2024-02-01, às 18 18 01
> when sending this
> 
> ```
> Image
> ```
> 
> it appears clickable on the preview but then when sending it isnt
> 
> Captura de ecrã 2024-02-01, às 18 21 18
> this is on dev
> 
> so im not saying it should be on dev in this case, but if is not gonna be clickable when sending should not be clickable in the preview

would create a new issue for that. as that problem is caused by the markdown preview js library

**Comment by stavares843** [comment]
sounds good, thanks! :hammer:

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
