### PR TITLE
update(SearchDropdown): Improve UI search dropdown users and groups

### LINKED ISSUE #926: improvement(sidebar): sidebar search should separate matching results from username and group chats
1. Go to Sidebar Search
2. Type any characters that should match only a result in the sidebar search
3. Multiple results are returned in sidebar even when these do not match with the search string (looking for "C" and getting results such as "Our Group" that do not contain a group name matching the search string, but contain usernames matching with search string

Update: As discussed during meeting today, we will display sidebar search results matching with the search string for usernames and also group names including a username matching with search string
We will have more details on the UI/UX for it soon. Changing the title of this as it is not a bug but just an improvement to the sidebar search

https://github.com/Satellite-im/Uplink/assets/35935591/da90cf9b-1f4e-492a-b9a9-0b6829d81f0e

### PR DESCRIPTION
**Pull request by lgmarchi**
### 4. Highlight chars typed on Users and group names 

https://github.com/Satellite-im/Uplink/assets/63157656/b14cf14e-8526-4a1d-adec-b3b9c72a6d98

### Which issue(s) this PR fixes 🔨

- Resolve #926 

### Additional comments 🎤
@phillsatellite and @stavares843 
There are 2 bugs, that will be better to fix in other PR.

### CODE REVIEW

**Comment by phillsatellite** [comment]
Made a suggestion to Lucas that underneath the group name we might want to add something to indicate that the usernames underneath are members of that group 

Screenshot 2023-08-16 at 4 19 54 PM

**Comment by lgmarchi** [comment]
> Made a suggestion to Lucas that underneath the group name we might want to add something to indicate that the usernames underneath are members of that group
> 
> Screenshot 2023-08-16 at 4 19 54 PM

Done my friend! 

image

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2023-08-17, às 16 35 37


the text is not very visible on light mode

macOS

**Review by stavares843 — COMMENTED** [review]
Captura de ecrã 2023-08-17, às 16 35 47


the ''members'' label is overlapping 


macOS

**Comment by lgmarchi** [comment]
> Captura de ecrã 2023-08-17, às 16 35 47
> the ''members'' label is overlapping
> 
> macOS

It is not member actually, problem is with long group name, let me try to fix it right now!

**Comment by lgmarchi** [comment]
> Captura de ecrã 2023-08-17, às 16 35 37
> the text is not very visible on light mode
> 
> macOS

@stavares843 I talked to @XileHorizon, for now, I will let highlight as link color, but we need a new ticket to discuss colors between themes.

**Comment by stavares843** [comment]
thanks 🔨 


https://github.com/Satellite-im/Uplink/assets/29093946/138058d1-d93f-44fb-9c5b-b515b76dbcd0



clicking on a user is not doing anything btw this is a user that i blocked/removed

**Comment by lgmarchi** [comment]
> thanks 🔨
> 
>  Gravacao.do.ecra.2023-08-17.as.19.50.00.mov 
> clicking on a user is not doing anything btw this is a user that i blocked/removed

Solution comitted.

**Comment by stavares843** [comment]
some chats are only opening if you try to click 2x

so you search, click, doesn't open the chat, search again, click again, now works


https://github.com/Satellite-im/Uplink/assets/29093946/7f562802-4468-4862-a761-0c88de7523e5

macOS

**Comment by lgmarchi** [comment]
> some chats are only opening if you try to click 2x
> 
> so you search, click, doesn't open the chat, search again, click again, now works
> 
>  Gravacao.do.ecra.2023-08-21.as.14.33.07.mov 
> macOS

Did you just try to find a friend and start a chat? No process before? I am asking because I am not able to replicate it

**Comment by stavares843** [comment]
no i just compiled > searched > clicked

**Comment by phillsatellite** [comment]
Sheldon and I both tried replicating the double click bug @stavares843 had mentioned above and haven't been able to on Mac/Linux/Windows

**Comment by lgmarchi** [comment]
> Sheldon and I both tried replicating the double click bug @stavares843 had mentioned above and haven't been able to on Mac/Linux/Windows

Good Phil, your Mac is M1 as well like Sara?

**Comment by phillsatellite** [comment]
> 

Tried on both 💥

**Comment by phillsatellite** [comment]
Approved by me once conflicting files are fixed 👍

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
