### PR TITLE
fix(panic): use Evan's fork until it gets merged into Dioxus

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- fixes a crash related to event bubbling
- had to comment out the tray feature temporarily because it wasn't in this fork
- had to change a function call related to using a specific Dioxus runtime in the emoji extension due to using this fork. 

### Which issue(s) this PR fixes 🔨

- Resolve #

### CODE REVIEW

**Comment by phillsatellite** [comment]
During testing I ran into a small issue, turned on dev mode/closed the app/re-opened and got ```error: process didn't exit successfully: `target\release\uplink.exe` (exit code: 0xe0000008)```

**Comment by tooshel** [comment]
> During testing I ran into a small issue, turned on dev mode/closed the app/re-opened and got `` error: process didn't exit successfully: `target\release\uplink.exe` (exit code: 0xe0000008) ``

And that's not happening on dev right? So strange . . . last time I tried I wasn't able to use the X in the top right but I'm trying this one soon.

**Comment by tooshel** [comment]
I'm on a windows 11 machine and when I turn on dev tools it crashes. 

image

I will send the crash log on discord. Is that what happens for you @phillsatellite?

**Comment by phillsatellite** [comment]
> I'm on a windows 11 machine and when I turn on dev tools it crashes.
> 
> image
> 
> I will send the crash log on discord. Is that what happens for you @phillsatellite?

My error seemed to be different I had (exit code: 0xe0000008) and it seems you had exit code 101

**Pull request closed without merging**
