### PR TITLE
fix(NoFriends): Fixes mascot becoming very wide

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖
Fixes wide mascot

Before:
image
After:
image

### CODE REVIEW

**Comment by phillsatellite** [comment]
Yo! Just noticed a small bug across all OS's it looks like everything on the friends page shifted to the right 

Screenshot 2023-11-17 at 3 20 44 PM

**Comment by luisecm** [comment]
> Yo! Just noticed a small bug across all OS's it looks like everything on the friends page shifted to the right
> 
> Screenshot 2023-11-17 at 3 20 44 PM

Yes, I saw the same behavior happened on the automated tests:
image

**Comment by InfamousVague** [comment]
Will get this patched up tomorrow, having a hard time debugging this with the crashing happening with non-release runs.

**Comment by InfamousVague** [comment]
Let me know if this fix helps

**Comment by phillsatellite** [comment]
Looking good on my end!

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
