### PR TITLE
feat(reactions): add message reactions

### LINKED ISSUE #529: UI - Implement reactions
image

the "react" button should let the user attach reactions. 

the Warp side is wired up. All that's needed is the UI. The pertinent code is here: 
image

It's possible that the emoji-picker for the emoji extension can serve as inspiration for the dialog for message reactions. 

For this first attempt, it may not be necessary to integrate the emoji extension with message reactions.

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- what the title says
- currently doesn't look good. needs UI work:
- the emojis are black/white
- we might want to render them differently, like giving them a different background color
- the 3rd picture shows an "emoji selector". it doesn't have a border and doesn't look like a popup. This especially needs fixing. 

### Which issue(s) this PR fixes 🔨

- Resolve #529 

### Additional comments 🎤

image
image
image

### CODE REVIEW

**Comment by dariusc93** [comment]
The emoji being black-and-white seems to only happen on linux (or at least under the distro im using). Could be made into a separate ticket to look into

**Comment by WanderingHogan** [comment]
This can go in before the UI change @phillsatellite if it gets approvals

**Comment by WanderingHogan** [comment]
@sdwoodbury this branch has something going on - segfaults, messages disappearing, etc. When you get a chance I can show you probably.

Sometimes right click stop working, random crashes, not only do messages you send pop up and disappear, but it will seemingly eat messages

**Comment by phillsatellite** [comment]
> @sdwoodbury this branch has something going on - segfaults, messages disappearing, etc. When you get a chance I can show you probably.
> 
> Sometimes right click stop working, random crashes, not only do messages you send pop up and disappear, but it will seemingly eat messages

I few things I was able to replicate 

- Edit messages seems to not be working, at least on my side. I verified I could still edit messages on dev branch

https://user-images.githubusercontent.com/93608357/231021119-769483b0-3a42-41f8-a2e3-5723ee4e8b8f.mov

- It seems that if User A react to a message, then on UserB side they will see the reaction x2. Vice verse for when User B reacts to a message, will appear x2 for User A 

User A side:
Screenshot 2023-04-10 at 7 52 26 PM

User B side:
Screenshot 2023-04-10 at 7 52 40 PM

When multiple people reacted to a message before they appeared like this:
Screenshot_2023-04-10_at_4 42 02_PM

But for me it just showed the duplicated reactions:
Screenshot 2023-04-10 at 7 59 56 PM

**Comment by dariusc93** [comment]
> @sdwoodbury this branch has something going on - segfaults, messages disappearing, etc. When you get a chance I can show you probably.
> 
> Sometimes right click stop working, random crashes, not only do messages you send pop up and disappear, but it will seemingly eat messages

Could you provide the segfaults? 

Does the issues you experience happen on dev?

**Comment by tooshel** [comment]
I experience the same on windows in debug mode. Didn't happen all day using dev. For the segfaults, do you just want a screenshot? How do we provide them? 
image

**Comment by dariusc93** [comment]
> I experience the same on windows in debug mode. Didn't happen all day using dev. For the segfaults, do you just want a screenshot? How do we provide them? image

Is this with or without the extensions?

**Comment by tooshel** [comment]
> Is this with or without the extensions?

No extensions. Is that the problem?

**Comment by dariusc93** [comment]
> > Is this with or without the extensions?
> 
> No extensions. Is that the problem?

Asked because if the extensions were loaded, i would suggested running without it first. Ill try to reproduce it on my end tomorrow but tonight i wasnt able to reproduce it under debug or release on linux or mac so maybe its something at random.

**Comment by tooshel** [comment]
It happened on Mac too for Hogan, only when I sent him a message. Not sure
the mix or what happened with phil but we can get more details to share so
you can replicate it.

**Comment by WanderingHogan** [comment]
This minor style commit just adds count and some css
Screenshot 2023-04-12 at 9 23 38 AM
Screenshot 2023-04-12 at 9 25 50 AM

When I get back I was trying to figure out how clicking the emoji to toggle your reaction would work. It needs to send the event to `ui/src/components/chat/compose.rs` and to show the user names in hover/alt of who reacted to a message, currently we build a string of dids in the `kit/src/components/message/mod.rs` but it is commented out

**Comment by phillsatellite** [comment]
@WanderingHogan the recent changes you made have fixed the duplicate issue and looks really good during my testing though one thing i couldn't get to work (maybe we can do this in another ticket) is getting the count to update. User A and User B both _thumbs up_ a message but count will still only display 1 reaction 


https://user-images.githubusercontent.com/93608357/231518501-67f2b72e-9973-47fa-8691-bfd12ead18cf.mov

**Comment by sdwoodbury** [comment]
> 

@phillsatellite  I believe I fixed this

**Comment by phillsatellite** [comment]
Works a lot better now at least on my side but it does seem to have moments when it doesnt want to update. Like on the most recent message most times if User A sends and reacts to the message when User B tries to react there is no update in the UI until they close down the app and re open. I replicated on all OS's if anyone would like I'd be more than happy to show in call or something. 

If this is minor and we want to merge in anyway, just let me know so I can create a ticket for it. 

https://user-images.githubusercontent.com/93608357/231612155-56f99da5-db06-4eaf-9caa-ec5e5c4f9dea.mov

**Comment by phillsatellite** [comment]
After Sheldon and I did some testing, we found that edit message still didnt seem to work and the reactions appear duplicated in group chats still. Other than that the recent commits made huge improvement's

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
