### PR TITLE
update(Storage): Start modal send files layout with one file selected

### LINKED ISSUE #1228: task(files): File should be pre-selected when sharing
**Issue:**
When you right+click a file to share and the chat/file selection modal pops up you are forced to re-select the file you originally wanted to share. 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/fc255200-99db-4738-bce8-efb5f387eb25

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Start modal send files layout with one file selected

https://github.com/Satellite-im/Uplink/assets/63157656/79444e5d-0744-41cc-aafc-55ceb3468eb3

### Which issue(s) this PR fixes 🔨

- Resolve #1228

### CODE REVIEW

**Comment by lgmarchi** [comment]
PR blocked until #1232 is merged.

**Review by dariusc93 — APPROVED** [review]

**Comment by phillsatellite** [comment]
Hello my friend, found a small issue when testing 

The file I wanted to share is pre selected which is awesome! But I did noticed I am unable to select any other files 

https://github.com/Satellite-im/Uplink/assets/93608357/2f4cc2a5-1789-49ff-97c4-0b00bcdc9208

**Comment by lgmarchi** [comment]
> Hello my friend, found a small issue when testing
> 
> The file I wanted to share is pre selected which is awesome! But I did noticed I am unable to select any other files
> 
>  Screen.Recording.2023-09-22.at.4.12.05.PM.mov

Fixed.

**Comment by phillsatellite** [comment]
Found a very small minor bug, sent to @lgmarchi to see if he would wanna address in this PR or a new one I think we are going to fix on this pr was minor and should be easy to fix 👍 

https://github.com/Satellite-im/Uplink/assets/93608357/2ae99302-c111-4aaa-9854-e127d0222ba1

**Review by phillsatellite — APPROVED** [review]

**Comment by lgmarchi** [comment]
> Found a very small minor bug, sent to @lgmarchi to see if he would wanna address in this PR or a new one I think we are going to fix on this pr was minor and should be easy to fix 👍
> 
>  Screen.Recording.2023-09-25.at.12.13.55.PM.mov

Fixed.

**Pull request merged**
