### PR TITLE
fix(ChatMessage): Fix send code on chatbar using enter key

### LINKED ISSUE #1514: bug(chat): Message doesnt clear from chatbar when sending code
**Issue:**
When you send a line of code and hit the enter key it doesnt seem to be clearing from the chatbar (Ive noticed sometimes it looks like it does clear until the user starts to scroll then code message is back in chatbar & also if you click send rather than hitting enter you can avoid this issue)

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/63cf97c0-cb63-45ee-b5a5-ea8398630921

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix send code on chatbar using enter key 

https://github.com/Satellite-im/Uplink/assets/63157656/bb674b4a-5fc9-4511-9fed-30799e19d3ae

### Which issue(s) this PR fixes 🔨

- Resolve #1514

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey bro, so when I tested I was still able to replicate bug. I pasted code, hit send key and message did not send. When I would scroll or switch to another chat the message would re appear back in the chatbar as if I never sent it 

I was able to replicate this on all OS's 

https://github.com/Satellite-im/Uplink/assets/93608357/fe88d2c6-3875-4578-a0a4-1a62655b8f23

**Comment by lgmarchi** [comment]
@phillsatellite I think other PR fixed this problem. Could we test dev branch and see the results? Instead of merge, we can close this PR.

**Comment by stavares843** [comment]
works fine here! cc @phillsatellite if that doesn't work for you let us know to reopen 🔨

**Comment by stavares843** [comment]
and thanks @lgmarchi 🎉

**Pull request closed without merging**
