### PR TITLE
fix(modal): Add conditional so modal will show for groups

### LINKED ISSUE #1690: bug(ui): View Group tooltip appears in 1on1 DM
**Issue:**
If you are in a 1on1 DM chat and you click the name at the top left of the chat, the View Group tooltip will appear 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/b483eece-14f8-43d5-ba3a-2502041e98ec

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- Add a check to ensure more than two people are in a chat to only show modal in a group

### Which issue(s) this PR fixes 🔨

- Resolve #1690

### CODE REVIEW

**Comment by phillsatellite** [comment]
Noticed a small bug that seems to be MacOS specific 

When I try to open the Members group chat model it doesnt seem to want to open. On Windows and Linux it works great 

https://github.com/Satellite-im/Uplink/assets/93608357/03e1ddbb-472b-45b2-908d-504f96192c06

**Comment by Jekrimo** [comment]
> Noticed a small bug that seems to be MacOS specific
> 
> When I try to open the Members group chat model it doesnt seem to want to open. On Windows and Linux it works great
> 
>  Screen.Recording.2024-01-12.at.1.46.20.PM.mov

Should be fixed! I'm not sure why but I think what was happening is that the other_participants() was referencing active_participants somehow. I'm not super familiar with how group structs work but that's my guess. Lemme know if you run into any problems, thank youuuuuu

**Comment by phillsatellite** [comment]
Hey dude! So I went back in and pulled the latest but still getting some funny behavior 

Its working great on Windows and Linux still but on Mac its about the same, 1on1 chats no longer have the group tooltip so thats working great but in group chats the members list still doesn't wanna open 

**Mac:**

https://github.com/Satellite-im/Uplink/assets/93608357/737cd8bf-cbf4-4404-884e-9d790121e828

**Windows / Linux**

https://github.com/Satellite-im/Uplink/assets/93608357/52fa46b9-87fd-46ae-a69b-ec87a3168356

**Comment by stavares843** [comment]
what phil mentioned also tried here and is the same 🔨

**Comment by Jekrimo** [comment]
> Hey dude! So I went back in and pulled the latest but still getting some funny behavior
> 
> Its working great on Windows and Linux still but on Mac its about the same, 1on1 chats no longer have the group tooltip so thats working great but in group chats the members list still doesn't wanna open
> 
> **Mac:**
> 
>  Mac.mov 
> **Windows / Linux**
> 
>  Windows.mp4

OY! Thank you for checking, I think I know what's up. If you are the creator of the group you get the edit button and not the modal, and vice versa if you are just added into the group, (not sure if you tried on accounts that were not admin of the group, it just messed me up for quite awhile so just putting it out there). This may be for not as Matt mentioned Saturday he may have an update for it anyways.

**Comment by stavares843** [comment]
closing after discussing with jeff as matt added this fix in another PR

**Pull request closed without merging**
