### PR TITLE
chore(General): Tweaked Lunar Eclipse theme and other small fixes.

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖

- addresses small bugs on the lunar eclipse theme

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
noticed that in the lunar eclipse theme the pre release copy gets hidden, is fine in the other themes

macOS


Captura de ecrã 2023-05-04, às 19 43 51

flow
- go to themes
- lunar eclipse theme
- appears as image in the left side - hidden
- change to other theme
- appears as the right side - not hidden

**Review by lgmarchi — COMMENTED** [review]
On Edit Group, label name users not appear. 
image

Name of the users are white as well.
image


Hover home on storage, it is showing white 
image

Not possible to see Banner Picture
image

**Comment by stavares843** [comment]
💥

**Comment by phillsatellite** [comment]
Lucas pretty much commented what I was going to but I wanted to include you cannot see the check mark on the add member to group feature 

Screenshot 2023-05-04 at 3 10 30 PM

**Comment by InfamousVague** [comment]
> noticed that in the lunar eclipse theme the pre release copy gets hidden, is fine in the other themes
> 
> macOS
> 
> Captura de ecrã 2023-05-04, às 19 43 51
> 
> flow
> 
>     * go to themes
> 
>     * lunar eclipse theme
> 
>     * appears as image in the left side - hidden
> 
>     * change to other theme
> 
>     * appears as the right side - not hidden

I don't get this bug anymore, it was resolved for me, make sure you switch the theme on and off again to apply the new changes maybe? 

image

**Comment by InfamousVague** [comment]
All should be good for testing now

**Comment by lgmarchi** [comment]
No hover effect on add or minus button 
image

Missing border on profile picture to be possible see difference between it and banner 
image

No background color on circle in this icon
image

This part of remove participants of group, is not possible to see clearly if we checking or not the check box
image

Still no name above Search users on edit group section
image

No hover effect on copy DID 
image

No hover effect on chat button on friends section 
image

No hover effect on Create Group Chat Button 
image

For some reason there is this scroll bar on Edit Group section as well 
image

I don't know if it is a bug from this branch, but X to close reply is very small 
image

**Comment by InfamousVague** [comment]
I think it's worth opening a new ticket for the other tweaks so we can get the current fixes in that will help all themes. Thoughts? I am happy to work on the new ticket right away as well so we can get this in.

**Comment by phillsatellite** [comment]
> I think it's worth opening a new ticket for the other tweaks so we can get the current fixes in that will help all themes. Thoughts? I am happy to work on the new ticket right away as well so we can get this in.

I'll write up these tickets today if we are gonna just merge 👍

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Comment by lgmarchi** [comment]
> I think it's worth opening a new ticket for the other tweaks so we can get the current fixes in that will help all themes. Thoughts? I am happy to work on the new ticket right away as well so we can get this in.

I agree Matt with new ticket for new fixes. 

But this one I think is critical, if possible, would be better to fix on this PR: 

image

**Review by lgmarchi — DISMISSED** [review]
Just fix this for approve, I think it is critical: 
image

**Comment by WanderingHogan** [comment]
@lgmarchi I will resolve that change request, good find

image
image

**Review by WanderingHogan — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]
Good to go!

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
**AI CODE REVIEW 🔨** 


Here's my feedback on the code changes:

In the first commit, the changes are straightforward and seem to match the commit message. No issues found.
In the second commit, there are multiple changes, but the commit message accurately describes them. Here are some specific comments:
The changes to indicator/mod.rs seem reasonable and match the commit message.
The changes to indicator/style.scss seem reasonable and match the commit message.

**Pull request merged**
