### PR TITLE
fix(chat): Fix char counter not updated right

### LINKED ISSUE #1167: bug(emoji): emoji counter not working properly on m2
From Phil:

So I tried on a m1 Mac and a m2 Mac. The m1 Mac worked great but on the M2 I had an issue of the emoji counter wouldn't show count until after you insert the emoji. The count would not clear out again until after you send another message with an emoji 

https://github.com/Satellite-im/Uplink/assets/93608357/f228f8cb-cb22-4a9a-84a5-b2a72e1494c5

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fixes the character counter not updated correctly
- I seem to be unable to reproduce luis bug where it shows e.g. `0/1024/1024`
- Also branch is kinda named wrong cause of the original issue name

### Which issue(s) this PR fixes 🔨

- Resolve #1167

### CODE REVIEW

**Comment by luisecm** [comment]
Looks like the error displayed on automated tests means that the emoji typed is not being counted in chars counter... 
"Testing..." + one emoji typed should display 11 chars instead of 10.

**Comment by stavares843** [comment]
thanks @luisecm 🔨

**Comment by stavares843** [comment]
> I seem to be unable to reproduce luis bug where it shows e.g. 0/1024/1024

is fixed on this branch 🔨 

that bug would appear just by compiling > going to a chat in macOS

**Comment by phillsatellite** [comment]
Noticed these while testing 

On MacOS the char counter will persist through other chats. So if User types 10 chars then switches chat counter will still say 10

https://github.com/Satellite-im/Uplink/assets/93608357/b3884004-aee1-467f-8e01-1f7c67adba50

Also noticed this on all OS's, after you send message char counter will appear as 0/1024/1024 until user starts typing again 

https://github.com/Satellite-im/Uplink/assets/93608357/5e44dc08-bfe7-434d-b7bf-4b0f951d994c

**Comment by Flemmli97** [comment]
> Noticed these while testing
> 
> On MacOS the char counter will persist through other chats. So if User types 10 chars then switches chat counter will still say 10
> 
>  Screen_Recording_2023-09-07_at_1.31.17_PM.mov 
> 
> Also noticed this on all OS's, after you send message char counter will appear as 0/1024/1024 until user starts typing again
> 
>  Screen.Recording.2023-09-07.at.1.32.59.PM.mov

that is like very strange. the first issue is the one this pr should fix in the first place and it does it for me :/


https://github.com/Satellite-im/Uplink/assets/34157027/dedadadf-dcad-4247-afac-c3dde3dd5eac

**Comment by phillsatellite** [comment]
@Flemmli97 Hello! Wanted to let you know that I retested this today and on Linux and Windows its working very very well. I did still replicate that MacOS bug though (Counter will persist when switching through chats)

https://github.com/Satellite-im/Uplink/assets/93608357/a88422b7-eb2a-459a-b29b-96c2bbc07d94

**Comment by Flemmli97** [comment]
closed as its now done in #1193

**Pull request closed without merging**
