### PR TITLE
task(groups): Add error toasts to group member removal

### LINKED ISSUE #1849: task(Groups): Show toast when trying to remove creator of group
**Task:** If you have permission to add/remove members of a group and you try to remove the creator an error will appear in terminal(See photo below). We should show a toast notification saying something along the lines of "Cannot remove creator of group!"

**OS:**
All

**Screenshot**
304583905-93c7009d-980f-4a9b-8f92-a6e356a7fd75

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- When attempting to remove a user from a group display a toast message if that process returns an error. E.g. via attempting to remove the groups creator

### Which issue(s) this PR fixes 🔨

- Resolve #1849

### CODE REVIEW

**Comment by phillsatellite** [comment]
Toast notification does happen but it flashes so quick that its very tough for the user to notice it. This behavior happens on all OS's

https://github.com/Satellite-im/Uplink/assets/93608357/0b1eb629-36e7-4d7b-bd82-47b9f474b7d6

**Comment by stavares843** [comment]
same here 🔨

**Comment by Flemmli97** [comment]
> Toast notification does happen but it flashes so quick that its very tough for the user to notice it. This behavior happens on all OS's
> 
>  Screen.Recording.2024-02-27.at.12.27.03.PM.mov

i found thats its related to this here:
https://github.com/Satellite-im/Uplink/blob/dev/ui/src/layouts/chats/mod.rs#L97

when in chat layout the toast gets immediately cleared.
does anyone know what the original crash was?

i tried commenting that part out and it no crash on my end. though i would assume thats some rare case in first place?

**Comment by stavares843** [comment]
i believe it was this one @Flemmli97 

PR

https://github.com/Satellite-im/Uplink/pull/1665

the line you mentioned

https://github.com/Satellite-im/Uplink/pull/1665/files#diff-0ffb5b9dac259853171eeff1059849b7859b8fc6542374ab340cc1766c661894R99

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://github.com/Satellite-im/Uplink/assets/29093946/90320a32-ed36-4465-845f-79281793d247



this is showing the toast when trying to remove the non owner of the group

error on log:

> 2024-03-04 19:26:58 | ERROR | ui/src/layouts/chats/presentation/chat/edit_group.rs:253 | failed to remove recipients from a group: Public key is invalid

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
as discussed in discord, since lucas added this one https://github.com/Satellite-im/Uplink/pull/1906, this PR is no longer needed

**Pull request closed without merging**
