### PR TITLE
chore(emoji): Fix issue where numbers and some symbols got big_emoji class applied

### LINKED ISSUE #1468: bug(chat): sending numbers the font is not displayed properly
STR:
- go to chat
- send a number
- the font is bigger

image

macOS, m1

### PR DESCRIPTION
**Pull request by WanderingHogan**
### What this PR does 📖
This is a workaround for the big numbers in chat, if you send them by themselves.

We rely on this crate: https://crates.io/crates/unic-emoji-char/0.8.0

That crate has this bug: https://github.com/open-i18n/rust-unic/issues/280

numbers and some symbols (like # and *) trigger the emoji checks from that crate.
- 

### Which issue(s) this PR fixes 🔨

- Resolve #1468

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]
coderabbit is very wrong regarding this PR. lol

**Comment by tooshel** [comment]
> coderabbit is very wrong regarding this PR. lol

This part? 
image

**Comment by phillsatellite** [comment]
@WanderingHogan  On all OS's this seems to break markdowns ☹️ 
Screenshot 2023-11-07 at 2 23 15 PM

**Comment by WanderingHogan** [comment]
@phillsatellite i think it is ready to try again, sorry about that

**Review by dariusc93 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
