### PR TITLE
fix(sidebar): mobile view sidebar would stick

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- when you downsize the app a "mobile view" on Linux everything works really well when you click a chat it goes into chat, switching pages shows correct page etc etc but on MacOS and Windows you cant click into chats, and sidebar will persist when switching between pages. 

### Which issue(s) this PR fixes 🔨

- Resolve #1008

### Special notes for reviewers 🗒️

Currently only tested on Mac!

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hi @Jekrimo so I was hoping to just approve this since it fixes both #971 and #972 but I did run into a minor issue. On Linux it seems to constantly stay in the mobile view no matter the size of the window 😔 

https://github.com/Satellite-im/Uplink/assets/93608357/11b2abab-0156-4468-9a28-25d9e506d4cc

**Comment by Jekrimo** [comment]
> Hi @Jekrimo so I was hoping to just approve this since it fixes both #971 and #972 but I did run into a minor issue. On Linux it seems to constantly stay in the mobile view no matter the size of the window 😔
> 
>  Screen.Recording.2023-07-18.at.4.16.33.PM.mov

I was afraid that would happen, lookin into it!

**Comment by lgmarchi** [comment]
@Jekrimo I recorded a video to help you, it just back to normal after 1200px

https://github.com/Satellite-im/Uplink/assets/63157656/d3a59d3b-448f-461b-aa22-9c36b3ebc634

**Comment by Jekrimo** [comment]
> @Jekrimo I recorded a video to help you, it just back to normal after 1200px
> 
>  Screen.Recording.2023-07-19.at.11.45.07.mov

Oh right! Yes, Linux is messed up as Phil found out yesterday

**Comment by sdwoodbury** [comment]
would it be better if a compile time flag checked if the build was for mobile? resizing a window isn't something one would do on mobile - maybe this is an easier way to address the issue. 

I noticed that on Desktop, other chat apps don't let the window get resized so small that there isn't room for both the sidebar and main part of the UI.

**Comment by Jekrimo** [comment]
> would it be better if a compile time flag checked if the build was for mobile? resizing a window isn't something one would do on mobile - maybe this is an easier way to address the issue.
> 
> I noticed that on Desktop, other chat apps don't let the window get resized so small that there isn't room for both the sidebar and main part of the UI.

I would be cool with setting a min-width that stops desktop and tablet users from making the window too small. I feel like we were going to try the mobile only build awhile back but dropped it for some reason, maybe @InfamousVague remembers?

**Comment by lgmarchi** [comment]
> > would it be better if a compile time flag checked if the build was for mobile? resizing a window isn't something one would do on mobile - maybe this is an easier way to address the issue.
> > I noticed that on Desktop, other chat apps don't let the window get resized so small that there isn't room for both the sidebar and main part of the UI.
> 
> I would be cool with setting a min-width that stops desktop and tablet users from making the window too small. I feel like we were going to try the mobile only build awhile back but dropped it for some reason, maybe @InfamousVague remembers?

I think we can set the min-width to 950, the way is today when we open the app, especially if we identify whether the system is windows, linux or macOS.

Other than that, min-width will need to be the exact size of the width of the tablet or mobile phone

**Comment by stavares843** [comment]
is this ready to test again? 🔨

**Comment by Jekrimo** [comment]
> is this ready to test again? 🔨

Now it should be!!! This should/might also conveniently fix 973

**Comment by dariusc93** [comment]
~~If this is closed, should https://github.com/Satellite-im/Uplink/pull/1038 also be closed or was this issue closed in error @Jekrimo?~~

Edit: Nevermind, thought this was an issue

**Comment by Jekrimo** [comment]
> ~If this is closed, should #1038 also be closed or was this issue closed in error @Jekrimo?~
> 
> Edit: Nevermind, thought this was an issue

It's my fault Darius, I was fighting some old code that kept pushing with my commits so I got slop with my branches, my bad and thanks for checking!!

**Pull request closed without merging**
