### PR TITLE
feat(sidebar): Add icon to hide/show sidebar

### LINKED ISSUE #268: UI - Add Hamburger icon to Sidebar
**Issue:** Should be cleared by @InfamousVague first but wanted to at least get a ticket started in case he approves. Luis and I were talking about how it would be cool to bring over the Hamburger icon we had in the Sidebar in Chore over to Uplink. This would make it so the User can close and/or open the sidebar while still in Desktop View 

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Adds an icon that when clicked on changes the sidebar to a minimalistic version (currently only containing the button to undo that) effectively hiding the sidebar
- Something to note is that whether sidebar is hidden/shown is not saved. Not sure though if we want to have it persistent in the first place or not

### Which issue(s) this PR fixes 🔨

- Resolve #268

### CODE REVIEW

**Review by sdwoodbury — COMMENTED** [review]
looks fine, though please make the `Cargo Workflow` pass.

**Comment by phillsatellite** [comment]
Really neat! I found a few things I wanted to mention but they seem minor, 

1. It looks like we could probably have the UI extend a bit further out to the left 

https://user-images.githubusercontent.com/93608357/228012216-ec853f5c-0286-4488-8fdc-4d478729b2c7.mov

2. If you are on mobile view and you use the hamburger icon to close the sidebar, instead of taking you back to the chat it takes you to a blank screen

https://user-images.githubusercontent.com/93608357/228012699-8f6f23ad-8bd8-48ed-bf5f-0c996890f7ab.mov

**Comment by Flemmli97** [comment]
> Really neat! I found a few things I wanted to mention but they seem minor,
> 
> 1. It looks like we could probably have the UI extend a bit further out to the left
> 
> 2. If you are on mobile view and you use the hamburger icon to close the sidebar, instead of taking you back to the chat it takes you to a blank screen

for 1.
thats cause the sidebar is still there but shrunk and not integrated into the main div. it would be nice in the future to have maybe other icons as shortcut there though. so keeping it like this might be beneficial

for 2.
from what im seeing it might be good to just disable this feature since from what it seems you only have either the sidebar or the other window (e.g. the chat window) shown anyway making this feature irrelevant

**Comment by phillsatellite** [comment]
> > Really neat! I found a few things I wanted to mention but they seem minor,
> > 
> > 1. It looks like we could probably have the UI extend a bit further out to the left
> > 2. If you are on mobile view and you use the hamburger icon to close the sidebar, instead of taking you back to the chat it takes you to a blank screen
> 
> for 1. thats cause the sidebar is still there but shrunk and not integrated into the main div. it would be nice in the future to have maybe other icons as shortcut there though. so keeping it like this might be beneficial
> 
> for 2. from what im seeing it might be good to just disable this feature since from what it seems you only have either the sidebar or the other window (e.g. the chat window) shown anyway making this feature irrelevant

Do you mean disable the mobile feature? Or disable the hamburger icon while in mobile view?

**Comment by Flemmli97** [comment]
> > > Really neat! I found a few things I wanted to mention but they seem minor,
> > > 
> > > 1. It looks like we could probably have the UI extend a bit further out to the left
> > > 2. If you are on mobile view and you use the hamburger icon to close the sidebar, instead of taking you back to the chat it takes you to a blank screen
> > 
> > 
> > for 1. thats cause the sidebar is still there but shrunk and not integrated into the main div. it would be nice in the future to have maybe other icons as shortcut there though. so keeping it like this might be beneficial
> > for 2. from what im seeing it might be good to just disable this feature since from what it seems you only have either the sidebar or the other window (e.g. the chat window) shown anyway making this feature irrelevant
> 
> Do you mean disable the mobile feature? Or disable the hamburger icon while in mobile view?

the icon

**Comment by phillsatellite** [comment]
> > > > Really neat! I found a few things I wanted to mention but they seem minor,
> > > > 
> > > > 1. It looks like we could probably have the UI extend a bit further out to the left
> > > > 2. If you are on mobile view and you use the hamburger icon to close the sidebar, instead of taking you back to the chat it takes you to a blank screen
> > > 
> > > 
> > > for 1. thats cause the sidebar is still there but shrunk and not integrated into the main div. it would be nice in the future to have maybe other icons as shortcut there though. so keeping it like this might be beneficial
> > > for 2. from what im seeing it might be good to just disable this feature since from what it seems you only have either the sidebar or the other window (e.g. the chat window) shown anyway making this feature irrelevant
> > 
> > 
> > Do you mean disable the mobile feature? Or disable the hamburger icon while in mobile view?
> 
> the icon

I think this would work. Any objections? @InfamousVague @WanderingHogan

**Comment by InfamousVague** [comment]
When the menu is collapsed, let's just show the "back button" in the top bar (if you click the mobile phone view and then click a route, you will see the back button) when the menu is hidden, instead of spending the screen real-estate on the left just for the button.

**Comment by InfamousVague** [comment]
image

**Comment by InfamousVague** [comment]
image

**Comment by Flemmli97** [comment]
> When the menu is collapsed, let's just show the "back button" in the top bar (if you click the mobile phone view and then click a route, you will see the back button) when the menu is hidden, instead of spending the screen real-estate on the left just for the button.

i am unsure what you mean by this. you mean keep it as it is currently on mobile without the hamburger icon?

**Comment by InfamousVague** [comment]
> > When the menu is collapsed, let's just show the "back button" in the top bar (if you click the mobile phone view and then click a route, you will see the back button) when the menu is hidden, instead of spending the screen real-estate on the left just for the button.
> 
> i am unsure what you mean by this. you mean keep it as it is currently on mobile without the hamburger icon?

Sorry, let's chat about this tomorrow it's easier to explain over screen share

**Review by phillsatellite — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]

**Pull request merged**
