### PR TITLE
chore(chatbar): disabling the chatbar when it's loading instead of displaying different text and not being multi line by default

### LINKED ISSUE #1254: chore(chatbar): disabling the chatbar when it's loading instead of displaying different text and not being multi line by default
Should change to just disabling the chatbar when it's loading instead of displaying different text. Should also not be multi-line by default.

image

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- give textarea min-height, add new translation for "loading...", remove "not friends anymore" message

### Which issue(s) this PR fixes 🔨

- Resolve #1254 

### Additional comments 🎤
Added in a change to textarea placeholder opacity

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Jeff! I just had a quick question. So is the goal for the textbox to say "Loading..." when logging in? 

On MacOS "Say Something..." still appeared and when I tested Windows it didnt say anything at all on the textbox. Just curious which was intended!

The height issue was fixed in both though 😄 

https://github.com/Satellite-im/Uplink/assets/93608357/eb2bf9b9-6bcd-4ec3-be1b-2e3fa81e2edd

**Comment by Jekrimo** [comment]
> Hey Jeff! I just had a quick question. So is the goal for the textbox to say "Loading..." when logging in?
> 
> On MacOS "Say Something..." still appeared and when I tested Windows it didnt say anything at all on the textbox. Just curious which was intended!
> 
> The height issue was fixed in both though 😄
> 
>  Screen.Recording.2023-10-26.at.10.34.43.AM.mov

Let me take a look, thanks Phill!!

**Comment by Jekrimo** [comment]
Fixed! Dumb notation mistake on my part, Tested windows and looks good! Testing Mac momentarily!

**Comment by stavares843** [comment]
let us know if we can retest 🔨 and thanks for fixing! 🎉

**Comment by Jekrimo** [comment]
> let us know if we can retest 🔨 and thanks for fixing! 🎉

Should be ready to test!

**Comment by stavares843** [comment]
thanks @Jekrimo! 🎉

**Comment by phillsatellite** [comment]
Hey Jeff! So it is looking pretty good on Windows and Linux but I did just replicate a crash a couple times that I couldnt do on dev 

If on MacOS you adjust the size of the app and then log out and log back in app will crash 

https://github.com/Satellite-im/Uplink/assets/93608357/eff919ce-08db-473b-aa63-d481c56546f3

**Review by sdwoodbury — APPROVED** [review]

**Comment by sdwoodbury** [comment]
@phillsatellite I think the crash is a separate issue. I doubt that changing some CSS and changing the text retrieved from the `main.ftl` file would cause a problem with hooks

**Comment by Jekrimo** [comment]
> @phillsatellite I think the crash is a separate issue. I doubt that changing some CSS and changing the text retrieved from the `main.ftl` file would cause a problem with hooks

I agree. I haven't been able to reproduce on my mac yet

**Comment by phillsatellite** [comment]
So I found that if I resize with emoji's installed on this branch the crash will happen. When I deleted my emoji extension and tried to replicate it worked fine

@sdwoodbury @Jekrimo

**Comment by Jekrimo** [comment]
Just tested with the emoji installed and still could not get the crash to occur.

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
