### PR TITLE
fix(sidebar): Fix sidebar being hidden/shown during undesired actions

### LINKED ISSUE #971: bug(responsive): Sidebar doesnt close when entering chat first time
**Issue:**
When you adjust your size of the app to resemble a mobile device and you try to enter a chat for the first time, the sidebar will not fully close. When you click the back button it will then fix this bug

**OS:**
MacOS
Windows 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/ca88c6a5-cc90-4689-837a-005fa5bd1a8f

### LINKED ISSUE #972: bug(responsive): Sidebar will persist when switching pages
**Issue:**
Adjust size of app to resemble a mobile device, when you switch tabs (ex going from files to friends) the sidebar will be open when you land on each page. When viewing on a mobile device we want the sidebar to be closed when switching pages. When a user switches to friends they should immediately see the friends page

**OS:**
MacOS

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/b1360477-d1be-4b01-ba4d-53731dddee86

### LINKED ISSUE #1126: bug(ui): Sidebar closes when entered chat *Linux only*
**Issue:**
When you enter a chat on Linux the sidebar will close each time 

**OS:**
Linux

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/ca1be6a6-a9b9-4cae-8cfe-d3d3cdcf6e0c

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Fix sidebar collapsing when not in minimal view and selecting a chat
- Fix sidebar not collapsing when switching between friend/chat/files etc. when in minimal view
- Fixes resize event using different window size value on mac which causes sidebar issues

### Which issue(s) this PR fixes 🔨

- Resolve #1126 (first point)
- Resolve #972 (second point)
- Resolve #971 (3rd point)

### Special notes for reviewers 🗒️

~~Minimal view is set differently on mac so this will not work there. Solution is in #1131~~

### CODE REVIEW

**Comment by phillsatellite** [comment]
Works perfect on Windows/Linux but having a lot of issues on MacOS 

-On Mac when you switch pages the sidebar will persist 
-When you try to enter chat, sidebar remains halfway open


https://github.com/Satellite-im/Uplink/assets/93608357/713cb105-db9c-4c5f-989c-5947cf5a7740

**Comment by Flemmli97** [comment]
should be fixed now

**Review by lgmarchi — APPROVED** [review]

**Comment by Flemmli97** [comment]
clippy errors cause variable needs to be mutable on macos only. not sure how we should handle that

**Comment by phillsatellite** [comment]
So on my Linux VM I was getting the warnings when compiling and after letting app sit for a little it would just close and show a core dumped error I replicated twice but havent been able to again since. Going to keep testing for a little to see if I can replicate again but wanted to throw a comment on here to see if you had any ideas 

Screenshot 2023-08-16 at 12 19 07 PM

Screenshot 2023-08-16 at 12 19 13 PM

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
Havent been able to replicate other than those 2 times, I also had Darius verify on actual Linux that the core dump did not happen. Good by me now, awesome PR @Flemmli97 🔥

**Review by dariusc93 — APPROVED** [review]

**Comment by dariusc93** [comment]
This can be merged but could you change the `minimal_width` signature to be immutable?

**Comment by Flemmli97** [comment]
> So on my Linux VM I was getting the warnings when compiling and after letting app sit for a little it would just close and show a core dumped error I replicated twice but havent been able to again since. Going to keep testing for a little to see if I can replicate again but wanted to throw a comment on here to see if you had any ideas
> 
> Screenshot 2023-08-16 at 12 19 07 PM Screenshot 2023-08-16 at 12 19 13 PM

ye im not sure how we should handle the warnings. on mac it needs to be mutable but on every other os it doesn't so the linter will complain on all but mac here

**Comment by stavares843** [comment]
Captura de ecrã 2023-08-16, às 23 23 39


missing linter 🔨

**Comment by Flemmli97** [comment]
> Captura de ecrã 2023-08-16, às 23 23 39
> missing linter 🔨

yes see above comment. idk how to have it mutable on mac only?

**Comment by stavares843** [comment]
@dariusc93 @lgmarchi @sdwoodbury any suggestions for the above? 🔨

**Comment by stavares843** [comment]
thanks @dariusc93 🔨

**Pull request merged**
