### PR TITLE
update(CharCounter): Fix char counter with emoji

### LINKED ISSUE #1144: bug(chat): char counter does not updating when selecting a emoji
luis noticed the following bug

STR:
- go to chat
- emoji
- select emoji
- char counter doesn't update

image

macOS

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1144

### CODE REVIEW

**Review by sdwoodbury — APPROVED** [review]

**Comment by sdwoodbury** [comment]
need to delete the space on line 158 of` textarea/mod.rs` to fix clippy

**Comment by phillsatellite** [comment]
So I tried on a m1 Mac and a m2 Mac. The m1 Mac worked great but on the M2 I had an issue of the emoji counter wouldnt show count until after you insert the emoji. The count would not clear out again until after you send another message with an emoji 

https://github.com/Satellite-im/Uplink/assets/93608357/f228f8cb-cb22-4a9a-84a5-b2a72e1494c5

**Comment by lgmarchi** [comment]
> So I tried on a m1 Mac and a m2 Mac. The m1 Mac worked great but on the M2 I had an issue of the emoji counter wouldnt show count until after you insert the emoji. The count would not clear out again until after you send another message with an emoji
> 
>  Screen.Recording.2023-08-23.at.2.33.53.PM.mov

In your Dev, on M2, is working?

**Comment by phillsatellite** [comment]
> 

also does not work on dev for the m2

**Comment by stavares843** [comment]
to add what phil mentioned, even thought it doesn't work in m2 for phil, i believe that was the goal of this PR 🔨 to fix what isn't working in dev that is related to this bug

**Comment by lgmarchi** [comment]
> to add what phil mentioned, even thought it doesn't work in m2 for phil, i believe that was the goal of this PR 🔨 to fix what isn't working in dev that is related to this bug

Actually, this bug not working on M2 was not goal for this PR. This PR was fixing not counting when we use emoji on chatBar. 

Now problem becomes a little bit more complex, because it is not just working on M2, but working on other computers.

**Comment by stavares843** [comment]
so do you prefer to fix the issue phil mentioned in a separate ticket, is that it? cc @lgmarchi 

also linter is failing 🔨

**Comment by lgmarchi** [comment]
> so do you prefer to fix the issue phil mentioned in a separate ticket, is that it? cc @lgmarchi
> 
> also linter is failing 🔨

I prefer that, but I would like to hear yours and @phillsatellite opinion. 

Should we open a new ticket or let it blocked until solve it?

**Comment by stavares843** [comment]
we can add a new one, thanks!

**Comment by stavares843** [comment]
missing linter to be merged 🔨

**Comment by stavares843** [comment]
added issue from phil here
https://github.com/Satellite-im/Uplink/issues/1167

**Pull request merged**
