### PR TITLE
fix(devtool): fix theme and tools bug

### PR DESCRIPTION
**Pull request by Jekrimo**
### Which issue(s) this PR fixes 🔨

#143

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hi Jeff! This works awesome, dev tools appear each time! I did find one super minor issue I tried replicated on dev but could only reproduce on here 

- So when you create an account and you go to Settings/General the Themes dropdown will appear fine. Now if you go to the Developer tab in Settings and toggle on Developer Mode and go back to the General tab the Themes dropdown will appear blank 

https://user-images.githubusercontent.com/93608357/214441550-73a49fc6-c1cd-4348-93f1-3d3c15ef02c1.mov

**Review by InfamousVague — APPROVED** [review]

**Comment by InfamousVague** [comment]
code looks good once QA approved 👍

**Comment by phillsatellite** [comment]
I got this error when trying to compile, assuming it might be due to the conflicts 

Screenshot 2023-01-27 at 1 24 35 PM

**Review by sdwoodbury — APPROVED** [review]
if this works then I approve the change. we may want to move Configuration into `State` in the future.

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
