### PR TITLE
fix(chatbar): don't close emoji picker on scroll

### LINKED ISSUE #1416: bug(chat): Emoji box closes when user scrolls up in chat
**Issue:**
When the user has the emoji box open and they scroll in chat it will automatically close on them 

**OS:**
All

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/4036eda8-749d-4609-900f-0b297ca93ccc

### PR DESCRIPTION
**Pull request by sdwoodbury**
### What this PR does 📖

- prevents the chatbar from auto-focusing while the emoji picker is open. 
- moved some `use_coroutines` into their own files, to make `get_chatbar` smaller. 

### Which issue(s) this PR fixes 🔨

- Resolve #1416 

### Additional comments 🎤
I bet the typing indicator causes the emoji picker to close. but that's a separate issue. one could probably fix that by removing the dependency on State.

### CODE REVIEW

**Comment by phillsatellite** [comment]
When tested the textbox in chat was greyed out and unable to click in to type a message. This was replicated on all os's 

https://github.com/Satellite-im/Uplink/assets/93608357/6e4366ae-87d8-4595-a902-dc7a8fbbdf95

**Comment by phillsatellite** [comment]
Hey Stu! So while testing I had some weird different behavior on each OS (I had verified about 3 times for each OS I was on the correct branch with the correct emoji extension installed) 

**MacOS:**
On Mac the emoji box would work for a minute but it seemed like as soon as the user starts to scroll back down, the emoji box would close 

https://github.com/Satellite-im/Uplink/assets/93608357/2b8911bf-0df9-4367-9eed-4397813fe4c9

**Windows & Linux:**
On Windows and Linux I couldnt get it to work at all, as soon as I scroll the emoji box would close (In screen recording I tried to show that I was on this branch because it had me second guessing myself, I also did delete my old emoji extension and replace it with the new one) It seems like the emoji box is closing as soon as the "Scroll to bottom" button appears

https://github.com/Satellite-im/Uplink/assets/93608357/16e7c3de-8237-4a4f-a844-1ec33c45b1a6

image

**Comment by sdwoodbury** [comment]
edit: nvm - it's probably the `onblur` handler in the extension

check it out - see this code here? 
image

one `Action` is `SetEmojiPickerVisible`. It's set from within the extension. When that happens, there's no debug log. State probably doesn't get updated, which explains why a re-render causes the emoji picker to close.

**Comment by phillsatellite** [comment]
Test should be failing since we merged Stu's audio fix PR in. Approved from my side

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
if you do : joy : and try to select the emoji doesn't get selected

doing the same in dev works fine

macOS, m1

**Review by stavares843 — APPROVED** [review]
after rebuilding again works fine now

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
