### PR TITLE
fix(Storage): Fix files grid in storage

### LINKED ISSUE #256: Grid will break while uploading files
**Issue:** While uploading files, eventually the grid will break and become scattered. In screenshot you can see top row has 5 followed by 7 followed by 6 followed by 8

**Screenshot:**
Screenshot 2023-02-06 at 11 25 22 AM

### PR DESCRIPTION
**Pull request by lgmarchi**
### 1. Fix files grid in files 
image

- 

### Which issue(s) this PR fixes 🔨

- Resolve #256

### CODE REVIEW

**Review by sdwoodbury — DISMISSED** [review]

**Review by dariusc93 — DISMISSED** [review]

**Comment by phillsatellite** [comment]
Hey Lucas! Just one small issue I ran into on MacOS and Windows. It seems all good until the user creates a folder, after folder is created it will break the grid

MacOS:

https://user-images.githubusercontent.com/93608357/218629477-d3129ca6-be03-41d7-b8ab-4e33b61af218.mov

Windows:
windows
WindowsMobile

**Comment by lgmarchi** [comment]
> Hey Lucas! Just one small issue I ran into on MacOS and Windows. It seems all good until the user creates a folder, after folder is created it will break the grid
> 
> MacOS:
> 
> Windows: windows WindowsMobile

Fixed my friend. 

And I added a code to focus on enter username when we are creating account as well: 

https://user-images.githubusercontent.com/63157656/218774434-d007557b-53bb-48f8-a31a-45d1b73dbbbf.mov

**Review by sdwoodbury — DISMISSED** [review]
nice

**Review by phillsatellite — DISMISSED** [review]

**Comment by phillsatellite** [comment]
All fixed on my side! One more dev review and we can merge this in 🔥

**Review by dariusc93 — DISMISSED** [review]

**Comment by sdwoodbury** [comment]
merge conflicts :(

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
