### PR TITLE
fix(scroll): add scroll to create group

### LINKED ISSUE #1007: bug(groups): Scroll is missing on create groups
**Issue:**
I noticed on dev branch the scroll is missing when creating a group, I tested a few commits and noticed it had been introduced in `43538b7f4f8cef751cc11554022f43634f8c1f2d` 

**OS:**
All 

**Screen recording:**

https://github.com/Satellite-im/Uplink/assets/93608357/24ca5f40-063f-4bf0-af66-6e80f89b0136

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- add scroll to group friend list for create group

### Which issue(s) this PR fixes 🔨

- Resolve #1007

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
still happens here


Captura de ecrã 2023-07-24, às 17 14 33


macOS, m1

**Comment by Jekrimo** [comment]
> still happens here
> 
> Captura de ecrã 2023-07-24, às 17 14 33
> macOS, m1

Looking into it, my Mac on Mobile view is working still which is weird
Screenshot 2023-07-25 at 11 03 02 AM

**Comment by stavares843** [comment]
is fixed now 🎉  shady

**Review by stavares843 — APPROVED** [review]

**Comment by Jekrimo** [comment]
> is fixed now 🎉 shady

Yeah, idk what the heck happened

**Review by phillsatellite — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Pull request merged**
