### PR TITLE
fix(Group): Fix crash on remove and add same member to the group

### LINKED ISSUE #1867: bug(groups): app crashes when adding back a user to a group chat
- Issue happens when user B leaves a group chat and User A adds user again. Then window from User A crashes
- Issue also happens when user B is removed from the group chat and User A adds user again. Then window from User A crashes

On MacOS

Steps to reproduce - Flow 1:

1. Create a group chat (UserA is owner) with at least two users
2. User B leaves the group chat
3. User A adds again User B to the group chat
4. User B is added back to the group as expected, but the app for User A crashes showing this in log:
[1]    74747 segmentation fault  

https://github.com/Satellite-im/Uplink/assets/35935591/eb1fbbbf-4bc3-420c-8b07-14421490f4fc

Steps to reproduce - Flow 2:

1. Create a group chat (UserA is owner) with at least two users
2. User A should remove User B from the group chat
3. User A adds again User B to the group chat
4. User B is added back to the group as expected, but the app for User A crashes showing this in log:
[1]    74747 segmentation fault  

https://github.com/Satellite-im/Uplink/assets/35935591/24d32897-daef-4e1f-827c-8080ad5a6e27

### PR DESCRIPTION
**Pull request by lgmarchi**
### Which issue(s) this PR fixes 🔨

- Resolve #1867

### CODE REVIEW

**Comment by luisecm** [comment]
We found the following issue on the automated test results: 

- After adding a user to Favorites, the heart button from the top is not refreshed and it's still showing Add To Favorites. Happening with normal chat and group chat
- After removing a user from Favorites, the heart button from the top is not refreshed and it's still showing Remove from Favorites. Happening with normal chat and group chat

https://github.com/Satellite-im/Uplink/assets/35935591/c41b8104-a137-402f-b914-d0f9cd266a6d

**Comment by lgmarchi** [comment]
> We found the following issue on the automated test results:
> 
>     * After adding a user to Favorites, the heart button from the top is not refreshed and it's still showing Add To Favorites. Happening with normal chat and group chat
> 
>     * After removing a user from Favorites, the heart button from the top is not refreshed and it's still showing Remove from Favorites. Happening with normal chat and group chat
> 
> 
> Grabacion.de.pantalla.2024-02-28.a.la.s.4.23.17.p.m.mov

Fixed

**Review by phillsatellite — APPROVED** [review]

**Comment by dariusc93** [comment]
Does this also fix what  https://github.com/Satellite-im/Uplink/pull/1885 is attempting to fix?

**Review by luisecm — APPROVED** [review]

**Comment by stavares843** [comment]
yes @dariusc93 ive closed that one instead

**Review by dariusc93 — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
